//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by pvengine.rc
//
#define IDC_STATUS_LABEL_FIRST          0
#define IDC_STATUS_LABEL_STATE          0
#define IDC_STATUS_LABEL_FRAME          1
#define IDC_STATUS_LABEL_LAST           9
#define IDC_STATUS_DATA_FIRST           10
#define IDC_STATUS_DATA_STATE           10
#define IDC_STATUS_DATA_FRAME           11
#define IDC_STATUS_DATA_LAST            19
#define IDC_STATUS_PROGRESS             20
#define IDC_STATUS_ID_LAST              20
#define CM_FIRST                        2000
#define CM_ALERT                        2000
#define CM_AUTORENDER                   2005
#define CM_CLEARQUEUE                   2010
#define CM_COMMANDLINE                  2015
#define CM_TOOLBARCMDLINE               2017
#define CM_CONTINUECURRENT              2020
#define CM_DEMO                         2025
#define CM_BENCHMARK                    2027
#define CM_BENCHMARKONETHREAD           2028
#define CM_RENDERSHOW                   2030
#define CM_DUMPPANE                     2035
#define CM_FILEEXIT                     2040
#define CM_FILEQUEUE                    2045
#define CM_FILERENDER                   2050
#define CM_STOPRENDER                   2051
#define CM_FORCE8BITS                   2055
#define CM_HELPABOUT                    2060
#define CM_HELPCONTENTS                 2065
#define CM_HELPBUGS                     2070
#define CM_HELPPOVWIN                   2080
#define CM_HELPSCENE                    2085
#define CM_HELPLOOKUP                   2087
#define CM_PRESERVEMESSAGES             2090
#define CM_RENDERACTIVE                 2095
#define CM_SOURCEFILE                   2130
#define CM_TILEDBACKGROUND              2140
#define CM_BACKGROUNDCOLOUR             2145
#define CM_BACKGROUNDBITMAP             2150
#define CM_TEXTCOLOUR_FIRST             2165
#define CM_TEXTCOLOUR_NORMAL            2165
#define CM_TEXTCOLOUR_WARNING           2166
#define CM_TEXTCOLOUR_ERROR             2167
#define CM_TEXTCOLOUR_LAST              2167
#define CM_FONT                         2175
#define CM_RENDERABOVEMAIN              2180
#define CM_SHELLOUTWAIT                 2185
#define CM_RENDERHIDE                   2190
#define CM_RENDERCLOSE                  2195
#define CM_RENDERDESTROY                2197
#define CM_CLEARMESSAGES                2200
#define CM_SAVE_SETTINGS                2205
#define CM_TIPOFTHEDAY                  2210
#define CM_SHOWNEXTTIP                  2215
#define CM_TINYCAPTION                  2220
#define CM_NONCLIENT                    2225
#define CM_HELPPOVCD                    2236
#define CM_HELPIRTCCD                   2237
#define CM_COMPLETION_EXIT              2240
#define CM_COMPLETION_MESSAGE           2243
#define CM_COMPLETION_NOTHING           2245
#define CM_COMPLETION_HAL               2247
#define CM_TRANSPARENCY_NONE            2250
#define CM_TRANSPARENCY_10              2251
#define CM_TRANSPARENCY_20              2252
#define CM_TRANSPARENCY_30              2253
#define CM_TRANSPARENCY_40              2254
#define CM_TRANSPARENCY_50              2255
#define CM_TRANSPARENCY_60              2256
#define CM_TRANSPARENCY_70              2257
#define CM_TRANSPARENCY_80              2258
#define CM_TRANSPARENCY_90              2259
#define CM_RENDERPRIORITY_BACKGROUND    2298
#define CM_RENDERPRIORITY_LOW           2300
#define CM_RENDERPRIORITY_NORMAL        2305
#define CM_RENDERPRIORITY_HIGH          2310
#define CM_PREVENTSLEEP                 2315
#define CM_FILEOPEN                     2325
#define CM_FILENEW                      2330
#define CM_FILESAVEAS                   2340
#define CM_FILESAVE                     2345
#define CM_USETEMPLATE                  2355
#define CM_POVLEGAL                     2360
#define CM_SYSTEMNOACTIVE               2370
#define CM_SINGLEINSTANCE               2375
#define CM_USETOOLBAR                   2385
#define CM_USETOOLTIPS                  2390
#define CM_PREVWINDOW                   2395
#define CM_NEXTWINDOW                   2400
#define CM_DROPEDITOR                   2410
#define CM_DROPRENDERER                 2415
#define CM_USEEDITOR                    2420
#define CM_RENDERAUTOCLOSE              2425
#define CM_RENDERSLEEP                  2430
#define CM_USEEXTENSIONS                2435
#define CM_SHOWMAINWINDOW               2440
#define CM_GOPOVRAYORG                  2450
#define CM_GOIRTC                       2455
#define CM_FILECLOSE                    2460
#define CM_IO_NO_RESTRICTIONS           2470
#define CM_IO_RESTRICT_WRITE            2471
#define CM_IO_RESTRICT_READWRITE        2472
#define CM_RW_SOURCE                    2475
#define CM_NO_SHELLOUTS                 2480
#define CM_SAVEIMAGE                    2485
#define CM_RENDERINSERT                 2490
#define CM_BACKGROUNDSTD                2700
#define CM_LOADTOOLMENU                 2800
#define CM_FIRSTTOOL                    2805
#define CM_LASTTOOL                     2855
#define CM_FIRSTEDITNOTIFY              2900
#define CM_LASTEDITNOTIFY               2925
#define CM_FIRSTMENUHELP                2930
#define CM_FILEMENUHELP                 2930
#define CM_EDITMENUHELP                 2931
#define CM_SEARCHMENUHELP               2932
#define CM_TEXTMENUHELP                 2933
#define CM_EDITORMENUHELP               2934
#define CM_RENDERMENUHELP               2935
#define CM_OPTIONSMENUHELP              2936
#define CM_TOOLSMENUHELP                2937
#define CM_GUIEXTMENUHELP               2938
#define CM_RENDERWINMENUHELP            2939
#define CM_MESSAGEWINMENUHELP           2940
#define CM_WINDOWMENUHELP               2941
#define CM_LASTMENUHELP                 2942
#define CM_HIDENEWUSERHELP              2945
#define CM_PRESERVERENDERBITMAP         2950
#define INSTANCE_COMMAND_MESSAGE        2955
#define CM_DUTYCYCLE_10                 2960
#define CM_DUTYCYCLE_20                 2961
#define CM_DUTYCYCLE_30                 2962
#define CM_DUTYCYCLE_40                 2963
#define CM_DUTYCYCLE_50                 2964
#define CM_DUTYCYCLE_60                 2965
#define CM_DUTYCYCLE_70                 2966
#define CM_DUTYCYCLE_80                 2967
#define CM_DUTYCYCLE_90                 2968
#define CM_DUTYCYCLE_100                2969
#define CM_CHECKNEWVERSION              2970
#define CM_SENDSYSTEMINFO               2972
#define CM_CHECKUPDATENOW               2974
#define CM_RENDERSOUNDS                 2980
#define CM_RENDERTHREADCOUNT            2983
#define CM_FIRSTVIDEOSOURCE             2990
#define CM_LASTVIDEOSOURCE              2999
#define IDC_COMMANDLINE                 4505
#define IDC_COPYRIGHT                   4510
#define IDC_GROUPBOX6                   4511
#define IDC_ACCESSORIES                 4512
#define IDC_GROUPBOX5                   4514
#define IDC_STATICTEXT1                 4515
#define IDC_STATICTEXT2                 4516
#define IDC_STATICTEXT3                 4517
#define IDC_STATICTEXT4                 4518
#define IDC_FILEQUEUE                   4520
#define IDC_CONTEXTHELP                 4521
#define IDC_LISTBOX                     4530
#define IDC_MESSAGES                    4535
#define IDC_READPOVLEGAL                4540
#define IDC_RENDER                      4545
#define IDC_RENDERa                     4546
#define IDC_SAVEPOVLEGAL                4555
#define IDC_SET                         4560
#define IDC_VERSION                     4565
#define IDC_ADDFILE                     4570
#define IDC_DELETEFILE                  4575
#define IDC_STATISTICS                  4585
#define IDC_BROWSEINIFILE               4625
#define IDC_BROWSESOURCEFILE            4635
#define IDC_GROUPBOX1                   4645
#define IDC_GROUPBOX2                   4650
#define IDC_GROUPBOX3                   4655
#define IDC_GROUPBOX4                   4660
#define IDC_COMMANDHELP                 4670
#define IDC_INIFILESECTION              4675
#define IDC_RELOADQUEUE                 4690
#define IDC_QUEUEENTRIES                4695
#define IDC_AUTORENDER                  4700
#define IDC_PRESETSOURCENAME            4705
#define IDC_PRESETSOURCEPATH            4710
#define IDC_INIFILENAME                 4715
#define IDC_INIFILEPATH                 4720
#define IDC_RESETINI                    4725
#define IDC_EDITINI                     4730
#define IDC_INIDEFAULT                  4735
#define IDC_SOURCEDEFAULT               4740
#define IDC_TOOLBAR                     4745
#define IDC_EDITRENDER                  4750
#define IDC_RTR                         4755
#define IDC_ADVICETEXT                  4760
#define IDC_DONTTELLMEAGAIN             4765
#define IDC_ENABLE_RENDERCOMPLETESOUND  4770
#define IDC_BROWSE_RENDERCOMPLETESOUND  4775
#define IDC_SOUND_RENDERCOMPLETE        4780
#define IDC_ENABLE_PARSEERRORSOUND      4785
#define IDC_BROWSE_PARSEERRORSOUND      4790
#define IDC_SOUND_PARSEERROR            4795
#define IDC_ENABLE_RENDERERRORSOUND     4800
#define IDC_BROWSE_RENDERERRORSOUND     4805
#define IDC_SOUND_RENDERERROR           4810
#define IDC_THREADCOUNT                 4820
#define IDC_THREADSPIN                  4825
#define IDC_VIDEOSOURCES                4830
#define IDC_ALTERNATEFILETEXT           4835
#define IDD_ABOUT                       6000
#define IDD_COMMANDLINE                 6005
#define IDD_SHORTCOMMANDLINE            6007
#define IDD_FILEQUEUE                   6010
#define IDD_TIP                         6015
#define IDD_VIEW                        6025
#define IDD_COMMFILE                    6030
#define IDD_FEATUREADVICE               6035
#define IDD_SOUNDS                      6040
#define IDD_THREADS                     6043
#define IDD_STATUSPANEL                 6045
#define IDD_RENDERALTERNATEFILE         6050
#define IDD_EXTENDEXPIRY                6055
#define IDI_PVENGINE_XP                 6500
#define IDI_RENDERWINDOW_XP             6505
#define IDI_PVENGINE                    6510
#define IDI_RENDERWINDOW                6515
#define PVENGINE_MENU                   6700
#define POPUP_MENUS                     6705
#define PVENGINE_MENU32                 6710
#define POPUP_MENUS32                   6715
#define BMP_BACKGROUND00                7000
#define BMP_BACKGROUND01                7001
#define BMP_BACKGROUND02                7002
#define BMP_BACKGROUND03                7003
#define BMP_BACKGROUND04                7004
#define BMP_ICON                        7110
#define BMP_REBAR                       7115
#define BMP_TINYBAR                     7121
#define BMP_STRETCHDIBITS               7124
#define BMP_LOGO_1                      7219
#define BMP_WIDEICON                    7220
#define BMP_TOOLFILENEW                 7300
#define BMP_TOOLFILEOPEN                7301
#define BMP_TOOLFILESAVE                7302
#define BMP_TOOLFILEQUEUE               7303
#define BMP_TOOLRENDERSHOW              7305
#define BMP_TOOLRENDERCLOSE             7306
#define BMP_TOOLCMDLINE                 7307
#define BMP_TOOLSOURCEFILE              7308
#define BMP_TOOLFILERENDER              7309
#define BMP_TOOLSTOPRENDER              7310
#define BMP_TOOLSLEEP                   7311
#define BMP_TOOLHELPCONT                7312
#define BMP_TOOLHELPPOVRAY              7313
#define BMP_TOOLHELPIRTCCD              7314
#define BMP_TOOLGOPOVRAY                7315
#define BMP_TOOLGOIRTC                  7316
#define BMP_TOOLSYSTRAY                 7317
#define BMP_TOOLHELPPOVCD               7318
#define BMP_TOOLFILECLOSE               7319
#define BMP_ABOUT                       7370
#define ID_REBAR                        8000
#define ID_STATUS                       8100
#define CM_FIRSTGUIEXT                  16384
#define CM_LASTGUIEXT                   20479
#define CM_FIRSTINSERTMENUITEM          21000
#define CM_LASTINSERTMENUITEM           29999
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        117
#define _APS_NEXT_COMMAND_VALUE         30055
#define _APS_NEXT_CONTROL_VALUE         1011
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
