//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by cmedit.rc
//
#define IDSAVE                          1001
#define IDSAVEALL                       1002
#define IDD_SAVEMODIFIED                1002
#define IDDISCARD                       1003
#define IDD_SAVEALLMODIFIED             1003
#define IDC_MESSAGE                     1004
#define IDD_RELOADFILE                  1004
#define IDRELOAD                        1005
#define IDD_SAVEBEFORERENDER            1005
#define IDC_CHECKBOX                    1006
#define IDD_ENTERVALUE                  1006
#define IDC_VSPLIT                      1006
#define IDC_SPIN                        1007
#define IDC_SPIN2                       1008
#define IDC_SPIN3                       1009
#define IDC_EDIT                        1010
#define IDC_SPIN4                       1010
#define IDC_POINTSIZE                   1011
#define IDC_SPIN5                       1012
#define IDC_USECOLOR                    1016
#define IDC_USEFANCYTEXT                1017
#define IDC_PAGENUMBERS                 1018
#define IDC_DATETIME                    1019
#define IDC_BORDERFIRST                 1020
#define IDC_BORDERNONE                  1020
#define IDC_BORDERTHIN                  1021
#define IDC_BORDERTHICK                 1022
#define IDC_BORDERLAST                  1022
#define IDC_FILENAME                    1030
#define IDD_PRINT                       1538
#define IDD_PRINTSETUP                  1539
#define IDD_PAGESETUP                   1546
#define CM_FIRST                        3100
#define CM_CUT                          3105
#define CM_COPY                         3110
#define CM_PASTE                        3115
#define CM_UNDO                         3125
#define CM_REDO                         3130
#define CM_TOGGLEBOOKMARK               3140
#define CM_FIRSTBOOKMARK                3145
#define CM_LASTBOOKMARK                 3150
#define CM_NEXTBOOKMARK                 3155
#define CM_PREVIOUSBOOKMARK             3160
#define CM_CLEARALLBOOKMARKS            3165
#define CM_SAVE                         3170
#define CM_SAVEAS                       3175
#define CM_SAVEALL                      3180
#define CM_OPENFILE                     3185
#define CM_CLOSEFILE                    3190
#define CM_PRINT                        3195
#define CM_FIND                         3200
#define CM_REPLACE                      3205
#define CM_FINDNEXT                     3210
#define CM_MATCHBRACE                   3220
#define CM_GOTOLINE                     3225
#define CM_INDENTSELECTION              3230
#define CM_INDENTSELECTIONPREVIOUS      3235
#define CM_UNDENTSELECTION              3240
#define CM_UPPERCASESELECTION           3245
#define CM_LOWERCASESELECTION           3250
#define CM_SPACESTOTABS                 3255
#define CM_TABSTOSPACES                 3260
#define CM_OPENFILEUNDERCURSOR          3270
#define CM_CLOSECURRENTFILE             3275
#define CM_CONTEXTHELP                  3280
#define CM_SHOWMESSAGES                 3285
#define CM_PROPERTIES                   3290
#define CM_FILEMENUHELP                 3295
#define CM_WINDOWMENUHELP               3300
#define CM_NEWFILE                      3305
#define CM_CLOSEALLFILES                3325
#define CM_CLOSEALLBUTTHIS              3326
#define CM_PAGESETUP                    3360
#define CM_EXIT                         3370
#define CM_OLDERFILES                   3380
#define CM_FILEBREAK                    3385
#define CM_SPLITHORIZONTALLY            3390
#define CM_SPLITVERTICALLY              3395
#define CM_DELETE                       3430
#define CM_SELECTALL                    3440
#define CM_SEARCHMENUHELP               3480
#define CM_TEXTMENUHELP                 3520
#define CM_SHOWWHITESPACE               3530
#define CM_SETREPEATCOUNT               3535
#define CM_SETTABSIZE                   3540
#define CM_EDITORMENUHELP               3610
#define CM_EDITMENUHELP                 3615
#define CM_AUTOLOADERRORFILE            3620
#define CM_SHOWPARSEMESSAGES            3625
#define CM_AUTOSAVE                     3630
#define CM_CREATEBACKUPS                3640
#define CM_UNDOAFTERSAVE                3645
#define CM_CURSORBEYONDEOL              3650
#define CM_CONSTRAINCARET               3655
#define CM_OVERLAYKEYWORDEXPANSION      3660
#define CM_CUSTOMCOLOURS                3715
#define CM_BLACKONWHITE                 3720
#define CM_WHITEONBLACK                 3725
#define CM_RECORDMACRO                  3735
#define CM_PLAYMACRO1                   3740
#define CM_PLAYMACRO2                   3745
#define CM_PLAYMACRO3                   3750
#define CM_PLAYMACRO4                   3755
#define CM_PLAYMACRO5                   3760
#define CM_PLAYMACRO6                   3765
#define CM_PLAYMACRO7                   3770
#define CM_PLAYMACRO8                   3775
#define CM_PLAYMACRO9                   3780
#define CM_PLAYMACRO10                  3785
#define CM_INSERTMENUHELP               3800
#define CM_EDITINSERTMENU               3805
#define CM_INDENTSTYLENONE              3900
#define CM_INDENTSTYLEFIRST             3900
#define CM_INDENTSTYLELANGUAGE          3901
#define CM_INDENTSTYLELAST              3902
#define CM_INDENTSTYLECOPY              3902
#define CM_SCROLLNONE                   3910
#define CM_SCROLLFIRST                  3910
#define CM_SCROLLHORIZONTAL             3911
#define CM_SCROLLVERTICAL               3912
#define CM_SCROLLLAST                   3913
#define CM_SCROLLBOTH                   3913
#define CM_AUTORELOADNEVER              3920
#define CM_AUTORELOADFIRST              3920
#define CM_AUTORELOADASK                3921
#define CM_AUTORELOADLAST               3922
#define CM_AUTORELOADALWAYS             3922
#define CM_FIRSTRECENTFILE              3930
#define CM_LASTRECENTFILE               3939
#define CM_FIRSTOLDERFILE               3940
#define CM_LASTOLDERFILE                3979
#define CM_OLDERFILES_DUMMYENTRY        3980
#define CM_SHIFTLEFT                    3990
#define CM_SHIFTRIGHT                   3991
#define CM_FIRSTWINDOW                  6000
#define CM_LASTWINDOW                   6099
#define CM_LAST                         6999
#define CM_FIRSTINSERTMENUITEM          21000
#define CM_LASTINSERTMENUITEM           29999
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1008
#define _APS_NEXT_COMMAND_VALUE         32786
#define _APS_NEXT_CONTROL_VALUE         1050
#define _APS_NEXT_SYMED_VALUE           1000
#endif
#endif
