// POVLAB version 4.00 SP4 - Included texture file.
// (C) 1994-1998, Denis Olivier.
// All rights reserved.
// Generated for POV-Ray (C) POV-Team, USA.
// Date=Tuesday 04-24-2001.
// Time=15:48:11.
// user_name=USER
// From=TEXTURE\POVLAB.INC
// For=E:\UTILIS~1\PHILIP~1\POVLAB~3\POVLAB\SCENE\LIGHT.SCN
// Textures found=1

#declare White_RPlastic = texture {
  pigment { color rgb <1, 1, 1,> }
  finish { phong 1.0 reflection 0.4 }
}

