// This work is licensed under the Creative Commons Attribution-ShareAlike 3.0 Unported License.
// To view a copy of this license, visit http://creativecommons.org/licenses/by-sa/3.0/ or send a
// letter to Creative Commons, 444 Castro Street, Suite 900, Mountain View, California, 94041, USA.

#ifndef(Stoneold_Inc_Temp)
#declare Stoneold_Inc_Temp = version;
#version 3.5;

#ifdef(View_POV_Include_Stack)
#   debug "including stoneold.inc\n"
#end

/*

              Persistence of Vision Raytracer Version 3.1

                  Stone textures by Mike Miller  1992
               Backwards-compatibility translation file.
           Translates old texture names to new texture names.
                     Use stones1.inc in the future.

*/

#include "stones1.inc"
#declare Grnt0   = texture { T_Grnt0   }
#declare Grnt1   = texture { T_Grnt1   }
#declare Grnt2   = texture { T_Grnt2   }
#declare Grnt3   = texture { T_Grnt3   }
#declare Grnt4   = texture { T_Grnt4   }
#declare Grnt5   = texture { T_Grnt5   }
#declare Grnt6   = texture { T_Grnt6   }
#declare Grnt7   = texture { T_Grnt7   }
#declare Grnt8   = texture { T_Grnt8   }
#declare Grnt9   = texture { T_Grnt9   }
#declare Grnt10  = texture { T_Grnt10  }
#declare Grnt11  = texture { T_Grnt11  }
#declare Grnt12  = texture { T_Grnt12  }
#declare Grnt13  = texture { T_Grnt13  }
#declare Grnt14  = texture { T_Grnt14  }
#declare Grnt15  = texture { T_Grnt15  }
#declare Grnt16  = texture { T_Grnt16  }
#declare Grnt17  = texture { T_Grnt17  }
#declare Grnt18  = texture { T_Grnt18  }
#declare Grnt19  = texture { T_Grnt19  }
#declare Grnt20  = texture { T_Grnt20  }
#declare Grnt21  = texture { T_Grnt21  }
#declare Grnt22  = texture { T_Grnt22  }
#declare Grnt23  = texture { T_Grnt23  }
#declare Grnt24  = texture { T_Grnt24  }
#declare Grnt25  = texture { T_Grnt25  }
#declare Grnt26  = texture { T_Grnt26  }
#declare Grnt27  = texture { T_Grnt27  }
#declare Grnt28  = texture { T_Grnt28  }
#declare Grnt29  = texture { T_Grnt29  }
#declare Grnt0a  = texture { T_Grnt0a  }
#declare Grnt1a  = texture { T_Grnt1a  }
#declare Grnt2a  = texture { T_Grnt2a  }
#declare Crack1  = texture { T_Crack1  }
#declare Crack2  = texture { T_Crack2  }
#declare Crack3  = texture { T_Crack3  }
#declare Crack4  = texture { T_Crack4  }
#declare Stone1  = texture { T_Stone1  }
#declare Stone2  = texture { T_Stone2  }
#declare Stone3  = texture { T_Stone3  }
#declare Stone4  = texture { T_Stone4  }
#declare Stone5  = texture { T_Stone5  }
#declare Stone6  = texture { T_Stone6  }
#declare Stone7  = texture { T_Stone7  }
#declare Stone8  = texture { T_Stone8  }
#declare Stone9  = texture { T_Stone9  }
#declare Stone10 = texture { T_Stone10 }
#declare Stone11 = texture { T_Stone11 }
#declare Stone12 = texture { T_Stone12 }
#declare Stone13 = texture { T_Stone13 }
#declare Stone14 = texture { T_Stone14 }
#declare Stone15 = texture { T_Stone15 }
#declare Stone16 = texture { T_Stone16 }
#declare Stone17 = texture { T_Stone17 }
#declare Stone18 = texture { T_Stone18 }
#declare Stone19 = texture { T_Stone19 }
#declare Stone20 = texture { T_Stone20 }
#declare Stone21 = texture { T_Stone21 }
#declare Stone22 = texture { T_Stone22 }
#declare Stone23 = texture { T_Stone23 }
#declare Stone24 = texture { T_Stone24 }

#version Stoneold_Inc_Temp;
#end
