#undef HAVE_XMU
#undef USE_X86_ASM
#undef USE_SPARC_ASM
#undef USE_3DNOW_ASM
#undef USE_SSE_ASM
#undef USE_MMX_ASM
#undef MESA_DEBUG
#undef MESA_TRACE
#undef FX
#undef FX_GLIDE3
#undef GGI
#undef SVGA
#undef USE_XSHM
#undef FAST_MATH
