/* ---------------------------------------------------------------------------
*  FLARE.C
*
*  Some Parts courtesy by Nathan KOPP.
*
*  from POVLAB 3D Modeller
*  Copyright 1994-1999 POVLAB Authors.
*  ---------------------------------------------------------------------------
*  NOTICE: This source code file is provided so that users may experiment
*  with enhancements to POVLAB and to port the software to platforms other
*  than those supported by the POVLAB authors. There are strict rules under
*  which you are permitted to use this file. The rules are in the file
*  named LEGAL.TXT which should be distributed with this file.
*  If LEGAL.TXT is not available or for more info please contact the POVLAB
*  primary author by leaving a message on http://www.povlab.org
*  The latest and official version of POVLAB may be found at this site.
*
*  POVLAB was originally written by Denis Olivier.
*
*  ---------------------------------------------------------------------------*/
#include <DIRECT.H>
#include <MATH.H>
#include <FLOAT.H>
#include <STDLIB.H>
#include <STDIO.H>
#include <STRING.H>
#include <PROCESS.H>
#include <DOS.H>
#include <TIME.H>
#include <GRAPH.H>
#include "LIB.H"
#include "GLOBAL.H"
#include "GLIB.H"

// ----------------------------------------------------------------------------
// --------- CHARGE LES PLUGINS EXISTANTS -------------------------------------
// ----------------------------------------------------------------------------
void flare_light(char *Light,int Bouton) {
  char Buffer[MAXPATH];
  char *Spec[2]={"1","*.FLR"};

  chdir("OBJECTS\\FLARE");

  strcpy(Buffer,selection_fichier(100,100,"LENS FLARE",Spec));
  if (Buffer[0]==27) return;
  strupr(Buffer);
  split_chemin(Light,Buffer,5);
  if (!strcmp(Light,"NONE.FLR")) {
    strcpy(Light,"None");
    strcpy(Bt[Bouton].Txt,"[none]");
  } else {
    strcpy(Bt[Bouton].Txt,Light);
  }
  affiche_bouton(Bouton);
}

// ----------------------------------------------------------------------------
// --------- WRITE THE LENS FLARE CODE ----------------------------------------
// ----------------------------------------------------------------------------
void write_lens_flare_code(FILE *File,DBL XL,DBL YL,DBL ZL,char *Flare) {
  // fprintf(File,"//    Lens Flare \"plug-in\" for POV-RAY 3.0\n");
  // fprintf(File,"//    Copyright (C) 1998           Nathan Kopp\n");
  // fprintf(File,"//    Version 4.0                 August, 1998\n");
  
  fprintf(File,"#declare light_loc = <%.4g,%.4g,%.4g>\n",XL,YL,ZL);
  fprintf(File,"#include \"%c:%s\\OBJECTS\\FLARE\\%s\"\n",NewLecteur[0],NewChemin,Flare);
  fprintf(File,"#declare CoordSys = \"pov\"\n");
  fprintf(File,"#declare no_lens_flare = 0\n");
  fprintf(File,"\n");
  fprintf(File,"// *****************************************************************\n");
  fprintf(File,"// ** set flare_amount and flare_brightness if the user specifies\n");
  fprintf(File,"// ** a bright background\n");
  fprintf(File,"//\n");
  fprintf(File,"#ifdef (bright_background)\n");
  fprintf(File,"  #if (bright_background)\n");
  fprintf(File,"    #ifndef (flare_amount)     #declare flare_amount     = 0.4 #end\n");
  fprintf(File,"    #ifndef (flare_brightness) #declare flare_brightness = 1.5 #end\n");
  fprintf(File,"  #end\n");
  fprintf(File,"#end\n");
  fprintf(File,"\n");
  fprintf(File,"// *****************************************************************\n");
  fprintf(File,"// ** Additional rotation degrees.\n");
  fprintf(File,"//\n");
  fprintf(File,"#ifndef (flare_rotate) #declare flare_rotate = 0 #end\n");
  fprintf(File,"#ifndef (flare_auto_rotate) #declare flare_auto_rotate = false #end\n");
  fprintf(File,"#ifndef (spots_auto_rotate) #declare spots_auto_rotate = false #end\n");
  fprintf(File,"\n");
  fprintf(File,"// *****************************************************************\n");
  fprintf(File,"// ** sizes for primary flare\n");
  fprintf(File,"//\n");
  fprintf(File,"#ifndef (source_size) #declare source_size = .02 #end\n");
  fprintf(File,"#ifndef (glow_size)   #declare glow_size   = .15 #end\n");
  fprintf(File,"#ifndef (ring_size)   #declare ring_size   = .3 #end\n");
  fprintf(File,"#ifndef (ring_width)  #declare ring_width  = .1 #end\n");
  fprintf(File,"\n");
  fprintf(File,"// *****************************************************************\n");
  fprintf(File,"// ** colors for primary flare\n");
  fprintf(File,"//\n");
  fprintf(File,"#ifndef (source_color)  #declare source_color  = <1, 1, 1> #end\n");
  fprintf(File,"#ifndef (glow_color)    #declare glow_color    = <1, 1, .7> #end\n");
  fprintf(File,"#ifndef (ring_color)    #declare ring_color    = <1, .7, .7> #end\n");
  fprintf(File,"#ifndef (source_bright) #declare source_bright = 2 #end\n");
  fprintf(File,"#ifndef (glow_bright)   #declare glow_bright   = 1.2 #end\n");
  fprintf(File,"\n");
  fprintf(File,"// *****************************************************************\n");
  fprintf(File,"// ** translucencies for primary flare\n");
  fprintf(File,"//\n");
  fprintf(File,"#ifndef (source_tr)   #declare source_tr   = .1 #end\n");
  fprintf(File,"#ifndef (glow_tr)     #declare glow_tr     = .7 #end\n");
  fprintf(File,"#ifndef (ring_tr)     #declare ring_tr     = .8 #end\n");
  fprintf(File,"#ifndef (source_fade) #declare source_fade = .20 #end\n");
  fprintf(File,"\n");
  fprintf(File,"// *****************************************************************\n");
  fprintf(File,"// ** attributes for big_glow\n");
  fprintf(File,"//\n");
  fprintf(File,"#ifndef (big_glow_size)  #declare big_glow_size  = 0 #end\n");
  fprintf(File,"#ifndef (big_glow_color) #declare big_glow_color = <1,1,1> #end\n");
  fprintf(File,"#ifndef (big_glow_tr)    #declare big_glow_tr    = 1 #end\n");
  fprintf(File,"\n");
  fprintf(File,"// *****************************************************************\n");
  fprintf(File,"// ** attributes for streaks\n");
  fprintf(File,"//\n");
  fprintf(File,"#ifndef (streak_a_size) #declare streak_a_size = 0 #end\n");
  fprintf(File,"#ifndef (streak_b_size) #declare streak_b_size = 0 #end\n");
  fprintf(File,"#ifndef (streak_a_tr)   #declare streak_a_tr   = 1 #end\n");
  fprintf(File,"#ifndef (streak_b_tr)   #declare streak_b_tr   = 1 #end\n");
  fprintf(File,"\n");
  fprintf(File,"// *****************************************************************\n");
  fprintf(File,"// ** default scale factors\n");
  fprintf(File,"//\n");
  fprintf(File,"#ifndef (main_flare_scale) #declare main_flare_scale = <1,1,1> #end\n");
  fprintf(File,"#ifndef (big_glow_scale)   #declare big_glow_scale = <1,1,1> #end\n");
  fprintf(File,"\n");
  fprintf(File,"// *****************************************************************\n");
  fprintf(File,"// ** attributes for star (sparkle)\n");
  fprintf(File,"//\n");
  fprintf(File,"#ifndef (star_color)  #declare star_color = <1,1,1> #end\n");
  fprintf(File,"#ifndef (star_tr)     #declare star_tr    = .9 #end\n");
  fprintf(File,"#ifndef (star_size)   #declare star_size  = .2 #end\n");
  fprintf(File,"#ifndef (star_size2)  #declare star_size2 = star_size / 2 #end\n");
  fprintf(File,"#ifndef (num_arms)    #declare num_arms   = 9 #end\n");
  fprintf(File,"#ifndef (num_arms2)   #declare num_arms2  = 9*2 #end\n");
  fprintf(File,"#ifndef (star_width)  #declare star_width = .1 #end\n");
  fprintf(File,"#ifndef (star_width2) #declare star_width2= .05 #end\n");
  fprintf(File,"#ifndef (star_rand)   #declare star_rand  = 0 #end\n");
  fprintf(File,"#ifndef (star_rand2)  #declare star_rand2 = 0 #end\n");
  fprintf(File,"#ifndef (star_seed) #declare star_seed = seed(55) #end\n");
  fprintf(File,"\n");
  fprintf(File,"#ifndef (star_mirror) #declare star_mirror = true #end\n");
  fprintf(File,"#ifndef (star_spread) #declare star_spread = true #end\n");
  fprintf(File,"#ifndef (crisp_star)  #declare crisp_star  = false #end\n");
  fprintf(File,"#ifndef (star_color_rand) #declare star_color_rand = 0 #end\n");
  fprintf(File,"#ifndef (star_size_rand) #declare star_size_rand = 0 #end\n");
  fprintf(File,"\n");
  fprintf(File,"// *****************************************************************\n");
  fprintf(File,"// ** attributes for spots\n");
  fprintf(File,"//\n");
  fprintf(File,"#ifndef (num_spots)      #declare num_spots     = 4 #end\n");
  fprintf(File,"#ifndef (opposite_spots) #declare opposite_spots= 4 #end\n");
  fprintf(File,"#ifndef (skip_spots)     #declare skip_spots    = 1 #end\n");
  fprintf(File,"#ifndef (spot_dist)      #declare spot_dist     = .2 #end\n");
  fprintf(File,"#ifndef (spot_dist_pwr)  #declare spot_dist_pwr = 2 #end\n");
  fprintf(File,"#ifndef (percent_dots)   #declare percent_dots    = 0 #end\n");
  fprintf(File,"#ifndef (percent_hex)    #declare percent_hex     = 0 #end\n");
  fprintf(File,"#ifndef (percent_pent)   #declare percent_pent    = 0 #end\n");
  fprintf(File,"\n");
  fprintf(File,"#ifndef (spot_size)     #declare spot_size     = .1 #end\n");
  fprintf(File,"#ifndef (spot_color)    #declare spot_color    = <1,1,.7> #end\n");
  fprintf(File,"#ifndef (spot_tr)       #declare spot_tr       = .9 #end\n");
  fprintf(File,"\n");
  fprintf(File,"#ifndef (dot_size)      #declare dot_size      = .04 #end\n");
  fprintf(File,"#ifndef (dot_color)     #declare dot_color     = <.4,1,.5> #end\n");
  fprintf(File,"#ifndef (dot_tr)        #declare dot_tr        = .75 #end\n");
  fprintf(File,"\n");
  fprintf(File,"// *****************************************************************\n");
  fprintf(File,"// ** randomness for spots\n");
  fprintf(File,"//\n");
  fprintf(File,"#ifndef (spot_seed)       #declare spot_seed       = seed(546) #end\n");
  fprintf(File,"#ifndef (spot_dist_rand)  #declare spot_dist_rand  = 0 #end\n");
  fprintf(File,"\n");
  fprintf(File,"#ifndef (spot_size_rand)  #declare spot_size_rand  = 1 #end\n");
  fprintf(File,"#ifndef (spot_color_rand) #declare spot_color_rand = 0 #end\n");
  fprintf(File,"#ifndef (dot_size_rand)   #declare dot_size_rand   = 1 #end\n");
  fprintf(File,"#ifndef (dot_color_rand)  #declare dot_color_rand  = 0 #end\n");
  fprintf(File,"#ifndef (spot_fade_amount)#declare spot_fade_amount= 0 #end\n");
  fprintf(File,"\n");
  fprintf(File,"// *****************************************************************\n");
  fprintf(File,"// ** Don't show flare source if they don't want us to\n");
  fprintf(File,"// *****************************************************************\n");
  fprintf(File,"#ifdef (show_flare_source) #if (show_flare_source = no)\n");
  fprintf(File,"   #declare source_tr = glow_tr\n");
  fprintf(File,"#end #end\n");
  fprintf(File,"\n");
  fprintf(File,"// *****************************************************************\n");
  fprintf(File,"// ** this is the size of the sphere that's around the camera\n");
  fprintf(File,"// *****************************************************************\n");
  fprintf(File,"#ifndef (disc_size)\n");
  fprintf(File,"  #ifdef (sphere_size)\n");
  fprintf(File,"    #declare disc_size = sphere_size\n");
  fprintf(File,"  #else\n");
  fprintf(File,"    #declare disc_size = .001\n");
  fprintf(File,"  #end\n");
  fprintf(File,"#end\n");
  fprintf(File,"\n");
  fprintf(File,"// *****************************************************************\n");
  fprintf(File,"// ** this is the scaling factor of the entire scene\n");
  fprintf(File,"// *****************************************************************\n");
  fprintf(File,"#ifndef (flare_size)\n");
  fprintf(File,"  #ifdef (flare_scale_factor)\n");
  fprintf(File,"    #declare flare_size = flare_scale_factor\n");
  fprintf(File,"  #else\n");
  fprintf(File,"    #declare flare_size = 1\n");
  fprintf(File,"  #end\n");
  fprintf(File,"#end\n");
  fprintf(File,"#ifndef (AmbientLight) #declare AmbientLight = <1,1,1> #end\n");
  fprintf(File,"\n");
  fprintf(File,"// *****************************************************************\n");
  fprintf(File,"// ************ DECLARE TRANSFORM VARIABLES ********************\n");
  fprintf(File,"// *****************************************************************\n");
  fprintf(File,"\n");
  fprintf(File,"// *****************************************************************\n");
  fprintf(File,"// ** compute relative location of camera to light source\n");
  fprintf(File,"// ** compute relative location of camera to center\n");
  fprintf(File,"// *****************************************************************\n");
  fprintf(File,"#declare lf_2light = cam_loc - light_loc\n");
  fprintf(File,"#declare lf_2ctr = cam_loc - lookat\n");
  fprintf(File,"\n");
  fprintf(File,"// Now project lf_2light onto lf_2ctr to find new lf_2ctr vector.  This gives us\n");
  fprintf(File,"// a vector from cam_loc to lf_2ctr that is perpendecular to the relative\n");
  fprintf(File,"// lookat vector.  The newctr vector is used in for multiple flare\n");
  fprintf(File,"// spot calculation.\n");
  fprintf(File,"#declare lf_newctr = lf_2ctr * vdot(lf_2light,lf_2ctr) / (vlength(lf_2ctr)*vlength(lf_2ctr))\n");
  fprintf(File,"\n");
  fprintf(File,"// *****************************************************************\n");
  fprintf(File,"// ** This hides the flare if it goes behind a planet\n");
  fprintf(File,"// *****************************************************************\n");
  fprintf(File,"#ifdef (planet_rad) #ifdef (light_rad) #ifdef (planet_loc)\n");
  fprintf(File,"  #declare lf_2planet = cam_loc - planet_loc\n");
  fprintf(File,"\n");
  fprintf(File,"  // *****************************************************************\n");
  fprintf(File,"  // ** Don't hide if light is in front of planet\n");
  fprintf(File,"  // *****************************************************************\n");
  fprintf(File,"  #if (vlength(lf_2light) > vlength(lf_2planet))\n");
  fprintf(File,"\n");
  fprintf(File,"     #declare lf_2light_p = lf_2light * vdot(lf_2planet,lf_2light) / (pow(vlength(lf_2light),2))\n");
  fprintf(File,"     #declare light_rad = light_rad * vlength(lf_2light_p) / vlength(lf_2light)\n");
  fprintf(File,"\n");
  fprintf(File,"     #declare lf_temp_vect = vnormalize(lf_2light_p) - vnormalize(lf_2light)\n");
  fprintf(File,"     // *****************************************************************\n");
  fprintf(File,"     // ** Careful -- don't hide if planet is on other side of camera\n");
  fprintf(File,"     // *****************************************************************\n");
  fprintf(File,"     #if ((lf_temp_vect.x = 0) & (lf_temp_vect.y = 0) & (lf_temp_vect.z = 0))\n");
  fprintf(File,"\n");
  fprintf(File,"        #declare lf_h = vlength(lf_2light_p - lf_2planet)\n");
  fprintf(File,"        #if (lf_h > (planet_rad + light_rad))\n");
  fprintf(File,"          #declare lf_visible = 1\n");
  fprintf(File,"          #declare lf_transmit = 0\n");
  fprintf(File,"        #else #if ( lf_h+light_rad < planet_rad )\n");
  fprintf(File,"          #declare lf_visible = 0\n");
  fprintf(File,"          #declare lf_transmit = 1\n");
  fprintf(File,"        #else\n");
  fprintf(File,"          #declare lf_area = pi*pow(light_rad,2)\n");
  fprintf(File,"\n");
  fprintf(File,"          #declare lf_x = ( pow(planet_rad,2) - pow(light_rad,2) + lf_h*lf_h ) / (2*lf_h)\n");
  fprintf(File,"          #declare lf_y = sqrt( pow(planet_rad,2) - lf_x*lf_x )\n");
  fprintf(File,"          #declare lf_theta = atan2(lf_y,lf_x)\n");
  fprintf(File,"          #declare lf_area1 = pow(planet_rad,2) * lf_theta - lf_x*lf_y\n");
  fprintf(File,"\n");
  fprintf(File,"          #declare lf_x = lf_h - lf_x\n");
  fprintf(File,"          #declare lf_y = sqrt( pow(light_rad,2) - lf_x*lf_x )\n");
  fprintf(File,"          #declare lf_theta = atan2(lf_y,lf_x)\n");
  fprintf(File,"          #declare lf_area2 = lf_area * lf_theta/pi - lf_x*lf_y\n");
  fprintf(File,"\n");
  fprintf(File,"          #declare lf_visible = (lf_area - (lf_area1+lf_area2)) / lf_area\n");
  fprintf(File,"          #declare lf_transmit = 1-lf_visible\n");
  fprintf(File,"\n");
  fprintf(File,"          #declare lf_intersect = vnormalize(lf_2light_p-lf_2planet) * lf_h\n");
  fprintf(File,"          #declare lf_vradius = (lf_2light_p-lf_2planet) + vnormalize(lf_2light_p-lf_2planet) * light_rad\n");
  fprintf(File,"          #declare lf_2light = lf_2planet + lf_intersect + (lf_vradius - lf_intersect) * pow(lf_transmit,2)\n");
  fprintf(File,"        #end #end\n");
  fprintf(File,"\n");
  fprintf(File,"        #warning \"\n\"\n");
  fprintf(File,"        #warning \"Percent of light visible is: \"\n");
  fprintf(File,"        #warning str(lf_visible*100,5,0)\n");
  fprintf(File,"        #warning \"\n\"\n");
  fprintf(File,"\n");
  fprintf(File,"        #ifdef(flare_shrink) #if (flare_shrink = true)\n");
  fprintf(File,"          #declare flare_size = flare_size * pow((1-lf_transmit/2),.5)\n");
  fprintf(File,"        #end #end\n");
  fprintf(File,"\n");
  fprintf(File,"        #if (lf_transmit = 1) #declare no_lens_flare = true #end\n");
  fprintf(File,"\n");
  fprintf(File,"        #declare star_tr = star_tr + (1-star_tr) * pow(lf_transmit,2)\n");
  fprintf(File,"        #declare glow_tr = glow_tr + (1-glow_tr) * pow(lf_transmit,2)\n");
  fprintf(File,"        #declare ring_tr = ring_tr + (1-ring_tr) * pow(lf_transmit,2)\n");
  fprintf(File,"        #declare source_tr = source_tr + (1-source_tr) * pow(lf_transmit,2)\n");
  fprintf(File,"        #declare spot_tr = spot_tr + (1-spot_tr) * pow(lf_transmit,2)\n");
  fprintf(File,"        #declare dot_tr = dot_tr + (1-dot_tr) * pow(lf_transmit,2)\n");
  fprintf(File,"        #declare big_glow_tr = big_glow_tr + (1-big_glow_tr) * pow(lf_transmit,2)\n");
  fprintf(File,"     #end\n");
  fprintf(File,"   #end\n");
  fprintf(File,"#end #end #end\n");
  fprintf(File,"\n");
  fprintf(File,"// *****************************************************************\n");
  fprintf(File,"// ** This hides the flare if it below a plane\n");
  fprintf(File,"// *****************************************************************\n");
  fprintf(File,"#ifdef (plane_loc) #ifdef (plane_norm) #ifdef (light_rad)\n");
  fprintf(File,"  #declare lf_to_plane = cam_loc - plane_loc\n");
  fprintf(File,"  #declare lf_area = pi*light_rad*light_rad\n");
  fprintf(File,"\n");
  fprintf(File,"  // *****************************************************************\n");
  fprintf(File,"  //  Plane equation:   a(x-x0) + b(y-y0) + c(z-z0) = 0\n");
  fprintf(File,"  //  To find if light is on same side of plane as camera\n");
  fprintf(File,"  // *****************************************************************\n");
  fprintf(File,"  #declare lf_hide_plane = vdot( (lf_2light-lf_to_plane), plane_norm)\n");
  fprintf(File,"  #declare lf_hide_plane = lf_hide_plane / abs(lf_hide_plane)\n");
  fprintf(File,"\n");
  fprintf(File,"  #declare lf_hide_plane2 = vdot( lf_to_plane, plane_norm)\n");
  fprintf(File,"  #declare lf_hide_plane2 = lf_hide_plane2 / abs(lf_hide_plane2)\n");
  fprintf(File,"  #if (lf_hide_plane2 > 0) #declare plane_norm = - plane_norm #end  // put camera on proper\n");
  fprintf(File,"                                                                    // side of plane\n");
  fprintf(File,"  #declare lf_hide_plane = lf_hide_plane - lf_hide_plane2\n");
  fprintf(File,"    // *****************************************************************\n");
  fprintf(File,"    //  zero = opposite sides, not zero = same side\n");
  fprintf(File,"\n");
  fprintf(File,"  #declare lf_b_vector = lf_2light - lf_to_plane\n");
  fprintf(File,"  #declare lf_d = abs( vdot(plane_norm, lf_b_vector) ) / vlength(plane_norm)\n");
  fprintf(File,"\n");
  fprintf(File,"  // *****************************************************************\n");
  fprintf(File,"  // ** set up area percents and top area percents\n");
  fprintf(File,"  // *****************************************************************\n");
  fprintf(File,"  #if ((lf_d < light_rad) & (lf_d != 0))\n");
  fprintf(File,"    #declare lf_x = sqrt( light_rad*light_rad - lf_d*lf_d)\n");
  fprintf(File,"    #declare lf_theta = atan2(lf_x, lf_d)\n");
  fprintf(File,"    #declare lf_a_pie = light_rad*light_rad * lf_theta\n");
  fprintf(File,"    #declare lf_a_tri = lf_x * lf_d\n");
  fprintf(File,"\n");
  fprintf(File,"    #if (lf_hide_plane = 0)  // ** other side\n");
  fprintf(File,"      #declare lf_area_per = (lf_a_pie - lf_a_tri) / lf_area\n");
  fprintf(File,"      #declare lf_top_area = pi * lf_x*lf_x / lf_area\n");
  fprintf(File,"    #else                    // ** same side\n");
  fprintf(File,"      #declare lf_area_per = (lf_area - lf_a_pie + lf_a_tri) / lf_area\n");
  fprintf(File,"      #declare lf_top_area = 1.00\n");
  fprintf(File,"    #end\n");
  fprintf(File,"  #else\n");
  fprintf(File,"    #if (lf_d = 0)\n");
  fprintf(File,"      #declare lf_area_per = .50\n");
  fprintf(File,"      #declare lf_top_area = 1.00\n");
  fprintf(File,"    #else  // d>r\n");
  fprintf(File,"      #if (lf_hide_plane = 0)  // ** other side\n");
  fprintf(File,"        #declare lf_area_per = 0.0\n");
  fprintf(File,"        #declare lf_top_area = 0.00\n");
  fprintf(File,"      #else                    // ** same side\n");
  fprintf(File,"        #declare lf_area_per = 1.0\n");
  fprintf(File,"        #declare lf_top_area = 1.00\n");
  fprintf(File,"      #end\n");
  fprintf(File,"    #end\n");
  fprintf(File,"  #end\n");
  fprintf(File,"\n");
  fprintf(File,"  #declare lf_theta = degrees (acos(vdot(-plane_norm,lf_2light) / (vlength(-plane_norm)*vlength(lf_2light))))\n");
  fprintf(File,"  #declare lf_theta = min(lf_theta,90)\n");
  fprintf(File,"  #declare lf_theta_per = lf_theta / 90\n");
  fprintf(File,"\n");
  fprintf(File,"  #declare lf_visible = lf_top_area + (lf_area_per - lf_top_area) * lf_theta_per\n");
  fprintf(File,"\n");
  fprintf(File,"  #if (lf_hide_plane = 0)  // ** other side\n");
  fprintf(File,"    #declare lf_2light = lf_2light + ((light_rad - lf_d)/4 + lf_d )*vnormalize(plane_norm)\n");
  fprintf(File,"  #else                    // ** same side\n");
  fprintf(File,"    #declare lf_2light = lf_2light + ((light_rad - lf_d)/4 )*vnormalize(plane_norm)\n");
  fprintf(File,"  #end\n");
  fprintf(File,"\n");
  fprintf(File,"  #warning \"\n\"\n");
  fprintf(File,"  #warning \"Percent of light visible is: \"\n");
  fprintf(File,"  #warning str(lf_visible*100,5,0)\n");
  fprintf(File,"  #warning \"\n\"\n");
  fprintf(File,"\n");
  fprintf(File,"  #declare lf_transmit = 1 - lf_visible\n");
  fprintf(File,"\n");
  fprintf(File,"  #ifdef(flare_shrink) #if (flare_shrink = true)\n");
  fprintf(File,"    #declare flare_size = flare_size * pow((1-lf_transmit/2),.5)\n");
  fprintf(File,"  #end #end\n");
  fprintf(File,"\n");
  fprintf(File,"  #if (lf_transmit = 1) #declare no_lens_flare = true #end\n");
  fprintf(File,"\n");
  fprintf(File,"  #declare star_tr = star_tr + (1-star_tr) * pow(lf_transmit,2)\n");
  fprintf(File,"  #declare glow_tr = glow_tr + (1-glow_tr) * pow(lf_transmit,2)\n");
  fprintf(File,"  #declare ring_tr = ring_tr + (1-ring_tr) * pow(lf_transmit,2)\n");
  fprintf(File,"  #declare source_tr = source_tr + (1-source_tr) * pow(lf_transmit,2)\n");
  fprintf(File,"  #declare spot_tr = spot_tr + (1-spot_tr) * pow(lf_transmit,2)\n");
  fprintf(File,"  #declare dot_tr = dot_tr + (1-dot_tr) * pow(lf_transmit,2)\n");
  fprintf(File,"  #declare big_glow_tr = big_glow_tr + (1-big_glow_tr) * pow(lf_transmit,2)\n");
  fprintf(File,"\n");
  fprintf(File,"#end #end #end\n");
  fprintf(File,"\n");
  fprintf(File,"\n");
  fprintf(File,"#ifdef (flare_amount)\n");
  fprintf(File,"   #declare lf_transmit = 1 - flare_amount\n");
  fprintf(File,"   #if (lf_transmit = 1) #declare no_lens_flare = true #end\n");
  fprintf(File,"\n");
  fprintf(File,"   #declare star_tr = star_tr + (1-star_tr) * pow(lf_transmit,1)\n");
  fprintf(File,"   #declare glow_tr = glow_tr + (1-glow_tr) * pow(lf_transmit,1)\n");
  fprintf(File,"   #declare ring_tr = ring_tr + (1-ring_tr) * pow(lf_transmit,1)\n");
  fprintf(File,"   #declare source_tr = source_tr + (1-source_tr) * pow(lf_transmit,1)\n");
  fprintf(File,"   #declare spot_tr = spot_tr + (1-spot_tr) * pow(lf_transmit,1)\n");
  fprintf(File,"   #declare dot_tr = dot_tr + (1-dot_tr) * pow(lf_transmit,1)\n");
  fprintf(File,"   #declare big_glow_tr = big_glow_tr + (1-big_glow_tr) * pow(lf_transmit,1)\n");
  fprintf(File,"#end\n");
  fprintf(File,"\n");
  fprintf(File,"// *****************************************************************\n");
  fprintf(File,"// ** compute rotation values for x and z axes\n");
  fprintf(File,"// *****************************************************************\n");
  fprintf(File,"#declare lf_2ctr = -lf_2ctr    #declare lf_2light = -lf_2light\n");
  fprintf(File,"\n");
  fprintf(File,"// ** project z onto lf_2ctr and subtract from z\n");
  fprintf(File,"#declare lf_newz = z - lf_2ctr * vdot(z,lf_2ctr) / pow(vlength(lf_2ctr),2)\n");
  fprintf(File,"#declare lf_newz = vnormalize(lf_newz)\n");
  fprintf(File,"\n");
  fprintf(File,"#declare lf_point_up = sky_vect - lf_2ctr * vdot(sky_vect,lf_2ctr) / pow(vlength(lf_2ctr),2)\n");
  fprintf(File,"#declare lf_point_ctr = lf_2light - lf_2ctr * vdot(lf_2light,lf_2ctr) / pow(vlength(lf_2ctr),2)\n");
  fprintf(File,"\n");
  fprintf(File,"// ** cross newz and lf_2ctr to get a vector perpendicular to both\n");
  fprintf(File,"#declare lf_perp = vcross(lf_2ctr,lf_newz)\n");
  fprintf(File,"\n");
  fprintf(File,"// ************************************\n");
  fprintf(File,"// ** Compute rotate towards sky vector\n");
  fprintf(File,"// ** project sky_vect onto perp\n");
  fprintf(File,"#declare lf_cdir = lf_perp * vdot(lf_point_up,lf_perp) / pow(vlength(lf_perp),2)\n");
  fprintf(File,"\n");
  fprintf(File,"#declare lf_rotate_up = z*degrees(acos(vdot(lf_point_up,lf_newz)/vlength(lf_point_up)))\n");
  fprintf(File,"#if (lf_cdir.x <= 0) #declare lf_rotate_up = -lf_rotate_up #end\n");
  fprintf(File,"\n");
  fprintf(File,"// ************************************\n");
  fprintf(File,"// ** Compute rotate towards center\n");
  fprintf(File,"// ** project sky_vect onto perp\n");
  fprintf(File,"#declare lf_cdir = lf_perp * vdot(lf_point_ctr,lf_perp) / pow(vlength(lf_perp),2)\n");
  fprintf(File,"\n");
  fprintf(File,"#declare lf_rotate_ctr = z*degrees(acos(vdot(lf_point_ctr,lf_newz)/vlength(lf_point_ctr)))\n");
  fprintf(File,"#if (lf_cdir.x <= 0) #declare lf_rotate_ctr = -lf_rotate_ctr #end\n");
  fprintf(File,"\n");
  fprintf(File,"#declare lf_rotate_x = -x*degrees(acos(vdot(lf_2ctr,z)/vlength(lf_2ctr)))\n");
  fprintf(File,"#declare lf_rotate_z = -z*degrees(atan2(lf_2ctr.x,lf_2ctr.y))\n");
  fprintf(File,"\n");
  fprintf(File,"#declare lf_2ctr = -lf_2ctr    #declare lf_2light = -lf_2light\n");
  fprintf(File,"\n");
  fprintf(File,"\n");
  fprintf(File,"// *****************************************************************\n");
  fprintf(File,"// ** randoms are relative to their respective variables\n");
  fprintf(File,"// *****************************************************************\n");
  fprintf(File,"#declare spot_dist_rand = spot_dist_rand * spot_dist\n");
  fprintf(File,"#declare spot_size_rand = spot_size_rand * spot_size\n");
  fprintf(File,"#declare dot_size_rand  = dot_size_rand * dot_size\n");
  fprintf(File,"#declare star_size_rand = star_size_rand * star_size\n");
  fprintf(File,"\n");
  fprintf(File,"// *****************************************************************\n");
  fprintf(File,"// ** set up lf_StarTex and lf_StarTex2 for the two sparkle textures\n");
  fprintf(File,"// *****************************************************************\n");
  fprintf(File,"\n");
  fprintf(File,"#declare lf_temp_tr = 1.0\n");
  fprintf(File,"#if (crisp_star = true) #declare lf_temp_tr = star_tr #end\n");
  fprintf(File,"\n");
  fprintf(File,"#if (num_arms > 0)\n");
  fprintf(File,"#declare lf_StarTex = pigment {\n");
  fprintf(File,"  radial\n");
  fprintf(File,"\n");
  fprintf(File,"  #if (star_mirror = true)\n");
  fprintf(File,"    frequency 2\n");
  fprintf(File,"    #declare lf_tmp_width = star_width / num_arms * 2\n");
  fprintf(File,"    #declare lf_ave_dist  = 1 / num_arms * 2\n");
  fprintf(File,"  #else\n");
  fprintf(File,"    frequency 1\n");
  fprintf(File,"    #declare lf_tmp_width = star_width / num_arms\n");
  fprintf(File,"    #declare lf_ave_dist  = 1 / num_arms\n");
  fprintf(File,"  #end\n");
  fprintf(File,"\n");
  fprintf(File,"  #declare lf_loc = 0\n");
  fprintf(File,"\n");
  fprintf(File,"  color_map{\n");
  fprintf(File,"    [0.0          color star_color transmit star_tr   ]\n");
  fprintf(File,"    [lf_tmp_width color star_color transmit lf_temp_tr]\n");
  fprintf(File,"    [lf_tmp_width color star_color transmit 1.0       ]\n");
  fprintf(File,"\n");
  fprintf(File,"    #declare lf_loc = lf_loc +  lf_ave_dist + (rand(star_seed)*2 - 1)*star_rand*(lf_ave_dist-2*lf_tmp_width)\n");
  fprintf(File,"    #while (lf_loc <(1-2*lf_tmp_width))\n");
  fprintf(File,"      #declare lf_s_color = star_color + star_color_rand * <(rand(star_seed) * 2 - 1),(rand(star_seed) * 2 - 1),(rand(spot_seed) * 2 - 1)>\n");
  fprintf(File,"      [lf_loc - lf_tmp_width  color lf_s_color transmit 1.0       ]\n");
  fprintf(File,"      [lf_loc - lf_tmp_width  color lf_s_color transmit lf_temp_tr]\n");
  fprintf(File,"      [lf_loc                 color lf_s_color transmit star_tr   ]\n");
  fprintf(File,"      [lf_loc + lf_tmp_width  color lf_s_color transmit lf_temp_tr]\n");
  fprintf(File,"      [lf_loc + lf_tmp_width  color lf_s_color transmit 1.0       ]\n");
  fprintf(File,"      #declare lf_loc = lf_loc +  lf_ave_dist + (rand(star_seed)*2 - 1)*star_rand*(lf_ave_dist-2*lf_tmp_width)\n");
  fprintf(File,"    #end\n");
  fprintf(File,"\n");
  fprintf(File,"    [1-lf_tmp_width color star_color transmit 1.0       ]\n");
  fprintf(File,"    [1-lf_tmp_width color star_color transmit lf_temp_tr]\n");
  fprintf(File,"    [1.0            color star_color transmit star_tr   ]\n");
  fprintf(File,"  }\n");
  fprintf(File,"\n");
  fprintf(File," rotate <90,0,-90>\n");
  fprintf(File,"}\n");
  fprintf(File,"#end\n");
  fprintf(File,"\n");
  fprintf(File,"#if (num_arms2 > 0)\n");
  fprintf(File,"#declare lf_StarTex2 = pigment {\n");
  fprintf(File,"  radial\n");
  fprintf(File,"  #if (star_mirror = true)\n");
  fprintf(File,"    frequency 2\n");
  fprintf(File,"    #declare lf_tmp_width = star_width2 / num_arms2 * 2\n");
  fprintf(File,"    #declare lf_ave_dist  = 1 / num_arms2 * 2\n");
  fprintf(File,"  #else\n");
  fprintf(File,"    frequency 1\n");
  fprintf(File,"    #declare lf_tmp_width = star_width2 / num_arms2\n");
  fprintf(File,"    #declare lf_ave_dist  = 1 / num_arms2\n");
  fprintf(File,"  #end\n");
  fprintf(File,"\n");
  fprintf(File,"  #declare lf_loc = 0\n");
  fprintf(File,"\n");
  fprintf(File,"  color_map{\n");
  fprintf(File,"    [0.0          color star_color transmit star_tr ]\n");
  fprintf(File,"    [lf_tmp_width color star_color transmit 1.0     ]\n");
  fprintf(File,"\n");
  fprintf(File,"    #declare lf_loc = lf_loc +  lf_ave_dist + (rand(star_seed)*2 - 1)*star_rand2*(lf_ave_dist-2*lf_tmp_width)\n");
  fprintf(File,"    #while (lf_loc <(1-2*lf_tmp_width))\n");
  fprintf(File,"      #declare lf_s_color = star_color + star_color_rand * <(rand(star_seed) * 2 - 1),(rand(star_seed) * 2 - 1),(rand(spot_seed) * 2 - 1)>\n");
  fprintf(File,"      [lf_loc - lf_tmp_width  color lf_s_color transmit 1.0    ]\n");
  fprintf(File,"      [lf_loc                 color lf_s_color transmit star_tr]\n");
  fprintf(File,"      [lf_loc + lf_tmp_width  color lf_s_color transmit 1.0    ]\n");
  fprintf(File,"      #declare lf_loc = lf_loc +  lf_ave_dist + (rand(star_seed)*2 - 1)*star_rand2*(lf_ave_dist-2*lf_tmp_width)\n");
  fprintf(File,"    #end\n");
  fprintf(File,"\n");
  fprintf(File,"    [1-lf_tmp_width color star_color transmit 1.0     ]\n");
  fprintf(File,"    [1.0            color star_color transmit star_tr ]\n");
  fprintf(File,"  }\n");
  fprintf(File,"\n");
  fprintf(File," rotate <90,0,-90>\n");
  fprintf(File,"}\n");
  fprintf(File,"#end\n");
  fprintf(File,"\n");
  fprintf(File,"#declare lf_PrimaryFlare = pigment {\n");
  fprintf(File,"  wood\n");
  fprintf(File,"  color_map {\n");
  fprintf(File,"     [ 0.0             color source_color*source_bright transmit source_tr ]\n");
  fprintf(File,"     [ source_size     color source_color*glow_bright transmit source_tr   ]\n");
  fprintf(File,"     [ source_size + (glow_size - source_size)*source_fade\n");
  fprintf(File,"                       color glow_color*glow_bright\n");
  fprintf(File,"                       transmit (source_tr+glow_tr)/2 ]\n");
  fprintf(File,"\n");
  fprintf(File,"     [ glow_size                 color glow_color   transmit glow_tr ]\n");
  fprintf(File,"     [ (glow_size + ring_size)/2 color glow_color   transmit 1       ]\n");
  fprintf(File,"\n");
  fprintf(File,"     [ (glow_size + ring_size)/2 color ring_color   transmit 1            ]\n");
  fprintf(File,"     [ (ring_size - ring_width * ring_size) color ring_color   transmit 1 ]\n");
  fprintf(File,"     [ ring_size                 color ring_color   transmit ring_tr      ]\n");
  fprintf(File,"     [ (ring_size + ring_width * ring_size) color ring_color   transmit 1 ]\n");
  fprintf(File,"     [ 1 color rgbt <0,0,0,1> ]\n");
  fprintf(File,"  } #ifdef (flare_scallop_wave) #if (flare_scallop_wave = yes) scallop_wave #end #end\n");
  fprintf(File,"}\n");
  fprintf(File,"\n");
  fprintf(File,"#declare lf_Finish = finish {\n");
  fprintf(File,"  refraction off\n");
  fprintf(File,"  specular 0\n");
  fprintf(File,"  phong 0\n");
  fprintf(File,"  diffuse 0.0\n");
  fprintf(File,"  reflection 0.0\n");
  fprintf(File,"\n");
  fprintf(File,"  #declare lf_bright = <1,1,1>\n");
  fprintf(File,"  #ifdef (AmbientLight)\n");
  fprintf(File,"    #declare lf_bright = lf_bright / AmbientLight\n");
  fprintf(File,"  #end\n");
  fprintf(File,"  #ifdef (flare_brightness)\n");
  fprintf(File,"    #declare lf_bright = lf_bright * flare_brightness\n");
  fprintf(File,"  #end\n");
  fprintf(File,"\n");
  fprintf(File,"  ambient lf_bright\n");
  fprintf(File,"}\n");
  fprintf(File,"\n");
  fprintf(File,"// *****************************************************************\n");
  fprintf(File,"// ** First, make sure the camera is in front of the camera by\n");
  fprintf(File,"//    checking the plane with normal from cam_loc to lookat.\n");
  fprintf(File,"//\n");
  fprintf(File,"//  Plane equation:   a(x-x0) + b(y-y0) + c(z-z0) = 0\n");
  fprintf(File,"//\n");
  fprintf(File,"// *****************************************************************\n");
  fprintf(File,"#ifdef(lookat)\n");
  fprintf(File,"  #declare cam_plane = 1 * vdot(lf_2ctr, lf_2light)\n");
  fprintf(File,"#else\n");
  fprintf(File,"  #declare cam_plane = 1  // assume flare in front of camera if no lookat given\n");
  fprintf(File,"#end\n");
  fprintf(File,"\n");
  fprintf(File,"#ifndef (lf_visible) #declare lf_visible = 1 #end\n");
  fprintf(File,"#if ((cam_plane < 0) | (no_lens_flare = true))\n");
  fprintf(File,"  #warning \"Light is behind camera or behind the planet.  Lens flare not created.\"\n");
  fprintf(File,"  // *****************************************************************\n");
  fprintf(File,"  // Skip lens flare completely... can have an impact on\n");
  fprintf(File,"  // render speed.\n");
  fprintf(File,"  // *****************************************************************\n");
  fprintf(File,"#else\n");
  fprintf(File,"\n");
  fprintf(File,"// *****************************************************************\n");
  fprintf(File,"// ********** THE ACTUAL DISCS FOR LENS FLARE **********************\n");
  fprintf(File,"// *****************************************************************\n");
  fprintf(File,"\n");
  fprintf(File,"#ifndef (lf_flares_drawn) #declare lf_flares_drawn = 0 #end\n");
  fprintf(File,"\n");
  fprintf(File,"#declare lf_new_disc_size = disc_size + .001 * lf_flares_drawn\n");
  fprintf(File,"disc {\n");
  fprintf(File,"  #declare lf_bound_y = (ring_size*(1+ring_width))/2\n");
  fprintf(File,"  <0,0,0>, z, lf_bound_y\n");
  fprintf(File,"\n");
  fprintf(File,"  texture {\n");
  fprintf(File,"    // ***************** Primary flare ********************\n");
  fprintf(File,"    pigment {\n");
  fprintf(File,"      lf_PrimaryFlare\n");
  fprintf(File,"    }\n");
  fprintf(File,"    finish { lf_Finish }\n");
  fprintf(File,"  }\n");
  fprintf(File,"  scale main_flare_scale * lf_new_disc_size * flare_size\n");
  fprintf(File,"\n");
  fprintf(File,"  #if (flare_auto_rotate = false)\n");
  fprintf(File,"    rotate lf_rotate_up\n");
  fprintf(File,"  #else\n");
  fprintf(File,"    rotate lf_rotate_ctr\n");
  fprintf(File,"  #end\n");
  fprintf(File,"  rotate flare_rotate*z\n");
  fprintf(File,"  rotate lf_rotate_x\n");
  fprintf(File,"  rotate lf_rotate_z\n");
  fprintf(File,"\n");
  fprintf(File,"  #declare lf_dist = 1/( vdot(lf_2light,lf_2ctr)/(vlength(lf_2ctr)*vlength(lf_2light)) )\n");
  fprintf(File,"  translate cam_loc + lf_new_disc_size * vnormalize(-lf_2light)*lf_dist\n");
  fprintf(File,"  no_shadow hollow\n");
  fprintf(File,"}\n");
  fprintf(File,"#declare lf_flares_drawn = lf_flares_drawn + 1\n");
  fprintf(File,"\n");
  fprintf(File,"#if ((num_arms > 0) | (num_arms2 > 0))\n");
  fprintf(File,"\n");
  fprintf(File,"#if (star_spread)\n");
  fprintf(File,"#declare lf_new_disc_size = disc_size + .001 * lf_flares_drawn\n");
  fprintf(File,"disc {\n");
  fprintf(File,"  #declare lf_bound_y = max(star_size*3,star_size2*3)/2\n");
  fprintf(File,"  <0,0,0>, z, lf_bound_y\n");
  fprintf(File,"  #if (num_arms > 0)\n");
  fprintf(File,"    texture {\n");
  fprintf(File,"      // ************** Star-type flare *********************\n");
  fprintf(File,"      pigment {\n");
  fprintf(File,"        wood\n");
  fprintf(File,"        pigment_map {\n");
  fprintf(File,"          [ 0.0            lf_StarTex]\n");
  fprintf(File,"          [ star_size      lf_StarTex]\n");
  fprintf(File,"          [ star_size * 3  lf_StarTex transmit 1]\n");
  fprintf(File,"          [ 1              lf_StarTex transmit 1]\n");
  fprintf(File,"        }\n");
  fprintf(File,"      }\n");
  fprintf(File,"      finish { lf_Finish }\n");
  fprintf(File,"    }\n");
  fprintf(File,"  #end\n");
  fprintf(File,"  #if (num_arms2 > 0)\n");
  fprintf(File,"    texture {\n");
  fprintf(File,"      // ************** Star-type2 flare *********************\n");
  fprintf(File,"      pigment {\n");
  fprintf(File,"        wood\n");
  fprintf(File,"        pigment_map {\n");
  fprintf(File,"          [ 0.0             lf_StarTex2]\n");
  fprintf(File,"          [ star_size2      lf_StarTex2]\n");
  fprintf(File,"          [ star_size2 * 3  lf_StarTex2 transmit 1 ]\n");
  fprintf(File,"          [ 1               lf_StarTex2 transmit 1 ]\n");
  fprintf(File,"        }\n");
  fprintf(File,"      }\n");
  fprintf(File,"      finish { lf_Finish }\n");
  fprintf(File,"    }\n");
  fprintf(File,"  #end\n");
  fprintf(File,"\n");
  fprintf(File,"  scale main_flare_scale * lf_new_disc_size * flare_size\n");
  fprintf(File,"\n");
  fprintf(File,"  #if (flare_auto_rotate = false)\n");
  fprintf(File,"    rotate lf_rotate_up\n");
  fprintf(File,"  #else\n");
  fprintf(File,"    rotate lf_rotate_ctr\n");
  fprintf(File,"  #end\n");
  fprintf(File,"  rotate flare_rotate*z\n");
  fprintf(File,"  rotate lf_rotate_x\n");
  fprintf(File,"  rotate lf_rotate_z\n");
  fprintf(File,"\n");
  fprintf(File,"  #declare lf_dist = 1/( vdot(lf_2light,lf_2ctr)/(vlength(lf_2ctr)*vlength(lf_2light)) )\n");
  fprintf(File,"  translate cam_loc + lf_new_disc_size * vnormalize(-lf_2light)*lf_dist\n");
  fprintf(File,"  no_shadow hollow\n");
  fprintf(File,"}\n");
  fprintf(File,"#declare lf_flares_drawn = lf_flares_drawn + 1\n");
  fprintf(File,"\n");
  fprintf(File,"#else // star_spread\n");
  fprintf(File,"  // **************************************\n");
  fprintf(File,"  // Create a bunch of streaks to simulate\n");
  fprintf(File,"  // the sparkle pattern\n");
  fprintf(File,"  //\n");
  fprintf(File,"#declare lf_tmp_num=2\n");
  fprintf(File,"#while (lf_tmp_num>0)\n");
  fprintf(File,"\n");
  fprintf(File,"  #if (lf_tmp_num = 2)\n");
  fprintf(File,"  #if (star_mirror)\n");
  fprintf(File,"    #declare lf_num = num_arms / 2\n");
  fprintf(File,"    #declare lf_tmp_width = star_width / num_arms * .25\n");
  fprintf(File,"    #declare lf_ave_ang  = 360 / num_arms // 2\n");
  fprintf(File,"  #else\n");
  fprintf(File,"    #declare lf_num = num_arms\n");
  fprintf(File,"    #declare lf_tmp_width = star_width / num_arms * .25\n");
  fprintf(File,"    #declare lf_ave_ang  = 360 / num_arms\n");
  fprintf(File,"  #end\n");
  fprintf(File,"  #else\n");
  fprintf(File,"  #if (star_mirror)\n");
  fprintf(File,"    #declare lf_num = num_arms2 / 2\n");
  fprintf(File,"    #declare lf_tmp_width = star_width2 / num_arms2 * .25\n");
  fprintf(File,"    #declare lf_ave_ang  = 360 / num_arms2 // 2\n");
  fprintf(File,"  #else\n");
  fprintf(File,"    #declare lf_num = num_arms2\n");
  fprintf(File,"    #declare lf_tmp_width = star_width2 / num_arms2 * .25\n");
  fprintf(File,"    #declare lf_ave_ang  = 360 / num_arms2\n");
  fprintf(File,"  #end\n");
  fprintf(File,"  #end\n");
  fprintf(File,"\n");
  fprintf(File,"  #while (lf_num > 0)\n");
  fprintf(File,"\n");
  fprintf(File,"    #if (lf_tmp_num = 2)\n");
  fprintf(File,"    #declare lf_tmp_size = star_size + (rand(star_seed) * 2 - 1) * star_size_rand\n");
  fprintf(File,"    #declare lf_tmp_ang  = lf_num * lf_ave_ang + (rand(star_seed) * 2 - 1) * star_rand * lf_ave_ang\n");
  fprintf(File,"    #declare lf_s_color = star_color + star_color_rand * <(rand(star_seed) * 2 - 1),(rand(star_seed) * 2 - 1),(rand(spot_seed) * 2 - 1)>\n");
  fprintf(File,"    #else\n");
  fprintf(File,"    #declare lf_tmp_size = star_size2 + (rand(star_seed) * 2 - 1) * star_size_rand\n");
  fprintf(File,"    #declare lf_tmp_ang  = lf_num * lf_ave_ang + (rand(star_seed) * 2 - 1) * star_rand2 * lf_ave_ang\n");
  fprintf(File,"    #declare lf_s_color = star_color + star_color_rand * <(rand(star_seed) * 2 - 1),(rand(star_seed) * 2 - 1),(rand(spot_seed) * 2 - 1)>\n");
  fprintf(File,"    #end\n");
  fprintf(File,"\n");
  fprintf(File,"    #declare lf_new_disc_size = disc_size + .001 * lf_flares_drawn\n");
  fprintf(File,"    disc {\n");
  fprintf(File,"      <0,0,0>, z, 1\n");
  fprintf(File,"      texture {\n");
  fprintf(File,"        pigment {\n");
  fprintf(File,"          wood\n");
  fprintf(File,"          ramp_wave\n");
  fprintf(File,"          color_map{\n");
  fprintf(File,"            [0.0 color lf_s_color transmit star_tr]\n");
  fprintf(File,"            #if (crisp_star=true)\n");
  fprintf(File,"              [1.0 color lf_s_color transmit star_tr]\n");
  fprintf(File,"            #else\n");
  fprintf(File,"              [1.0 color lf_s_color transmit 1.0]\n");
  fprintf(File,"            #end\n");
  fprintf(File,"          }\n");
  fprintf(File,"        }\n");
  fprintf(File,"        finish { lf_Finish }\n");
  fprintf(File,"      }\n");
  fprintf(File,"\n");
  fprintf(File,"      scale <lf_tmp_size,lf_tmp_width,1> * lf_new_disc_size * flare_size\n");
  fprintf(File,"      #if (star_mirror=false)\n");
  fprintf(File,"        scale <.5,1,1>\n");
  fprintf(File,"        translate <.5,0,0>*lf_tmp_size* lf_new_disc_size.x * flare_size.x\n");
  fprintf(File,"      #end\n");
  fprintf(File,"\n");
  fprintf(File,"      #if (flare_auto_rotate = false)\n");
  fprintf(File,"        rotate lf_rotate_up\n");
  fprintf(File,"      #else\n");
  fprintf(File,"        rotate lf_rotate_ctr\n");
  fprintf(File,"      #end\n");
  fprintf(File,"      rotate (lf_tmp_ang + flare_rotate)*z\n");
  fprintf(File,"      rotate lf_rotate_x\n");
  fprintf(File,"      rotate lf_rotate_z\n");
  fprintf(File,"\n");
  fprintf(File,"      #declare lf_dist = 1/( vdot(lf_2light,lf_2ctr)/(vlength(lf_2ctr)*vlength(lf_2light)) )\n");
  fprintf(File,"      translate cam_loc + lf_new_disc_size * vnormalize(-lf_2light)*lf_dist\n");
  fprintf(File,"      no_shadow hollow\n");
  fprintf(File,"    }\n");
  fprintf(File,"    #declare lf_flares_drawn = lf_flares_drawn + 1\n");
  fprintf(File,"    #declare lf_num = lf_num - 1\n");
  fprintf(File,"  #end\n");
  fprintf(File,"#declare lf_tmp_num = lf_tmp_num-1\n");
  fprintf(File,"#end //while\n");
  fprintf(File,"\n");
  fprintf(File,"#end // star_spread\n");
  fprintf(File,"\n");
  fprintf(File,"\n");
  fprintf(File,"#end\n");
  fprintf(File,"\n");
  fprintf(File,"// ************** streak_a flare *********************\n");
  fprintf(File,"#declare lf_new_disc_size = disc_size + .001 * lf_flares_drawn\n");
  fprintf(File,"#if ((streak_a_size > 0) & (streak_a_tr < 1))\n");
  fprintf(File,"  disc {\n");
  fprintf(File,"    <0,0,0>, z, .5\n");
  fprintf(File,"    texture {\n");
  fprintf(File,"      pigment {\n");
  fprintf(File,"        wood\n");
  fprintf(File,"        color_map {\n");
  fprintf(File,"           [ 0.0  color streak_a_center_color transmit streak_a_tr ]\n");
  fprintf(File,"           [ 1.0  color streak_a_color transmit 1           ]\n");
  fprintf(File,"        }\n");
  fprintf(File,"      }\n");
  fprintf(File,"      finish { lf_Finish }\n");
  fprintf(File,"    }\n");
  fprintf(File,"    scale streak_a_scale * streak_a_size * lf_new_disc_size * flare_size\n");
  fprintf(File,"\n");
  fprintf(File,"    #if (streak_a_auto_rotate = false)\n");
  fprintf(File,"      rotate lf_rotate_up\n");
  fprintf(File,"    #else\n");
  fprintf(File,"      rotate lf_rotate_ctr\n");
  fprintf(File,"    #end\n");
  fprintf(File,"    rotate streak_a_rotate*z\n");
  fprintf(File,"    rotate lf_rotate_x\n");
  fprintf(File,"    rotate lf_rotate_z\n");
  fprintf(File,"\n");
  fprintf(File,"    #declare lf_dist = 1/( vdot(lf_2light,lf_2ctr)/(vlength(lf_2ctr)*vlength(lf_2light)) )\n");
  fprintf(File,"    translate cam_loc + lf_new_disc_size * vnormalize(-lf_2light)*lf_dist\n");
  fprintf(File,"    no_shadow hollow\n");
  fprintf(File,"  }\n");
  fprintf(File,"  #declare lf_flares_drawn = lf_flares_drawn + 1\n");
  fprintf(File,"#end\n");
  fprintf(File,"\n");
  fprintf(File,"// ************** streak_b flare *********************\n");
  fprintf(File,"#declare lf_new_disc_size = disc_size + .001 * lf_flares_drawn\n");
  fprintf(File,"#if ((streak_b_size > 0) & (streak_b_tr < 1))\n");
  fprintf(File,"  disc {\n");
  fprintf(File,"    <0,0,0>, z, .5\n");
  fprintf(File,"    texture {\n");
  fprintf(File,"      pigment {\n");
  fprintf(File,"        wood\n");
  fprintf(File,"        color_map {\n");
  fprintf(File,"           [ 0.0  color streak_b_center_color transmit streak_b_tr ]\n");
  fprintf(File,"           [ 1.0  color streak_b_color transmit 1           ]\n");
  fprintf(File,"        }\n");
  fprintf(File,"      }\n");
  fprintf(File,"      finish { lf_Finish }\n");
  fprintf(File,"    }\n");
  fprintf(File,"    scale streak_b_scale * streak_b_size * lf_new_disc_size * flare_size\n");
  fprintf(File,"\n");
  fprintf(File,"    #if (streak_b_auto_rotate = false)\n");
  fprintf(File,"      rotate lf_rotate_up\n");
  fprintf(File,"    #else\n");
  fprintf(File,"      rotate lf_rotate_ctr\n");
  fprintf(File,"    #end\n");
  fprintf(File,"    rotate streak_b_rotate*z\n");
  fprintf(File,"    rotate lf_rotate_x\n");
  fprintf(File,"    rotate lf_rotate_z\n");
  fprintf(File,"\n");
  fprintf(File,"    #declare lf_dist = 1/( vdot(lf_2light,lf_2ctr)/(vlength(lf_2ctr)*vlength(lf_2light)) )\n");
  fprintf(File,"    translate cam_loc + lf_new_disc_size * vnormalize(-lf_2light)*lf_dist\n");
  fprintf(File,"    no_shadow hollow\n");
  fprintf(File,"  }\n");
  fprintf(File,"  #declare lf_flares_drawn = lf_flares_drawn + 1\n");
  fprintf(File,"#end\n");
  fprintf(File,"\n");
  fprintf(File,"// ************** big_glow flare *********************\n");
  fprintf(File,"#declare lf_new_disc_size = disc_size + .001 * lf_flares_drawn\n");
  fprintf(File,"#if ((big_glow_size > 0) & (big_glow_tr < 1))\n");
  fprintf(File,"  disc {\n");
  fprintf(File,"    #declare lf_bound_y = big_glow_size/2\n");
  fprintf(File,"    <0,0,0>, z, lf_bound_y\n");
  fprintf(File,"    texture {\n");
  fprintf(File,"      pigment {\n");
  fprintf(File,"        wood\n");
  fprintf(File,"        color_map {\n");
  fprintf(File,"           [ 0.0           color big_glow_color transmit big_glow_tr ]\n");
  fprintf(File,"           [ big_glow_size color big_glow_color transmit 1           ]\n");
  fprintf(File,"           [ 1 color       rgbt <0,0,0,1> ]\n");
  fprintf(File,"        }\n");
  fprintf(File,"      }\n");
  fprintf(File,"      finish { lf_Finish }\n");
  fprintf(File,"    }\n");
  fprintf(File,"    scale big_glow_scale * lf_new_disc_size * flare_size\n");
  fprintf(File,"\n");
  fprintf(File,"    #if (flare_auto_rotate = false)\n");
  fprintf(File,"      rotate lf_rotate_up\n");
  fprintf(File,"    #else\n");
  fprintf(File,"      rotate lf_rotate_ctr\n");
  fprintf(File,"    #end\n");
  fprintf(File,"    rotate lf_rotate_x\n");
  fprintf(File,"    rotate lf_rotate_z\n");
  fprintf(File,"\n");
  fprintf(File,"    #declare lf_dist = 1/( vdot(lf_2light,lf_2ctr)/(vlength(lf_2ctr)*vlength(lf_2light)) )\n");
  fprintf(File,"    translate cam_loc + lf_new_disc_size * vnormalize(-lf_2light)*lf_dist\n");
  fprintf(File,"    no_shadow hollow\n");
  fprintf(File,"  }\n");
  fprintf(File,"  #declare lf_flares_drawn = lf_flares_drawn + 1\n");
  fprintf(File,"#end\n");
  fprintf(File,"\n");
  fprintf(File,"//  *********************************************************************\n");
  fprintf(File,"//  *********************  Multiple lens flare spots ********************\n");
  fprintf(File,"//  *********************************************************************\n");
  fprintf(File,"#declare num_spots = num_spots + skip_spots\n");
  fprintf(File,"#declare opposite_spots = opposite_spots + skip_spots\n");
  fprintf(File,"\n");
  fprintf(File,"#while (num_spots > skip_spots)\n");
  fprintf(File,"  // *****************************************************************\n");
  fprintf(File,"  // ** randomly shift various attributes\n");
  fprintf(File,"  // *****************************************************************\n");
  fprintf(File,"  #declare lf_s_size  = spot_size + (rand(spot_seed) * 2 - 1) * spot_size_rand\n");
  fprintf(File,"  #declare lf_s_dist  = (rand(spot_seed) * 2 - 1) * spot_dist_rand\n");
  fprintf(File,"  #declare lf_s_color = spot_color + spot_color_rand * <(rand(spot_seed) * 2 - 1),(rand(spot_seed) * 2 - 1),(rand(spot_seed) * 2 - 1)>\n");
  fprintf(File,"  #declare lf_d_size  = dot_size + (rand(spot_seed) * 2 - 1) * dot_size_rand\n");
  fprintf(File,"  #declare lf_d_color = dot_color + dot_color_rand * <(rand(spot_seed) * 2 - 1),(rand(spot_seed) * 2 - 1),(rand(spot_seed) * 2 - 1)>\n");
  fprintf(File,"\n");
  fprintf(File,"  #declare lf_pentagon = false\n");
  fprintf(File,"\n");
  fprintf(File,"  #declare lf_is_dot = rand(spot_seed)\n");
  fprintf(File,"\n");
  fprintf(File,"  #switch (lf_is_dot)\n");
  fprintf(File,"  #range (0,percent_dots)\n");
  fprintf(File,"    #declare lf_SpotPigment = pigment {\n");
  fprintf(File,"      wood\n");
  fprintf(File,"      #declare tmp_tr = dot_tr + (1-dot_tr)*spot_fade_amount*(num_spots - skip_spots)\n");
  fprintf(File,"      color_map {\n");
  fprintf(File,"         [ 0.0                        color lf_d_color transmit tmp_tr         ]\n");
  fprintf(File,"         [ lf_d_size / 1.2            color lf_d_color transmit (1+tmp_tr)*.53 ]\n");
  fprintf(File,"         [ lf_d_size                  color lf_d_color transmit 1              ]\n");
  fprintf(File,"         [ 1 color rgbt <0,0,0,1> ]\n");
  fprintf(File,"      }\n");
  fprintf(File,"    }\n");
  fprintf(File,"    #declare lf_bound_y = lf_d_size/2\n");
  fprintf(File,"  #break\n");
  fprintf(File,"\n");
  fprintf(File,"  #range (percent_dots,percent_dots+percent_hex)\n");
  fprintf(File,"    #declare tmp_tr = spot_tr + (1-spot_tr)*spot_fade_amount*(num_spots - skip_spots)\n");
  fprintf(File,"    #declare lf_SpotPigment = pigment{hexagon lf_s_color transmit tmp_tr,rgbt<1,1,1,1>,rgbt<1,1,1,1> rotate 90*x scale .5*lf_s_size}\n");
  fprintf(File,"    #declare lf_bound_y = lf_s_size/2\n");
  fprintf(File,"  #break\n");
  fprintf(File,"\n");
  fprintf(File,"  #range (percent_dots+percent_hex,percent_dots+percent_hex+percent_pent)\n");
  fprintf(File,"    #declare lf_pentagon = true\n");
  fprintf(File,"    #declare tmp_tr = spot_tr + (1-spot_tr)*spot_fade_amount*(num_spots - skip_spots)\n");
  fprintf(File,"    #declare lf_SpotPigment = pigment{color lf_s_color transmit tmp_tr}\n");
  fprintf(File,"    #declare lf_bound_y = lf_s_size/2\n");
  fprintf(File,"  #break\n");
  fprintf(File,"\n");
  fprintf(File,"  #else\n");
  fprintf(File,"    #declare lf_SpotPigment = pigment {\n");
  fprintf(File,"      wood\n");
  fprintf(File,"      #declare tmp_tr = spot_tr + (1-spot_tr)*spot_fade_amount*(num_spots - skip_spots)\n");
  fprintf(File,"      color_map {\n");
  fprintf(File,"         [ 0.0                       color lf_s_color transmit 1              ]\n");
  fprintf(File,"         [ lf_s_size / 1.8           color lf_s_color transmit (1+tmp_tr)*.53 ]\n");
  fprintf(File,"         [ lf_s_size                 color lf_s_color transmit tmp_tr         ]\n");
  fprintf(File,"         [ lf_s_size +.1 * lf_s_size color lf_s_color transmit 1              ]\n");
  fprintf(File,"         [ 1 color rgbt <0,0,0,1> ]\n");
  fprintf(File,"      }\n");
  fprintf(File,"    }\n");
  fprintf(File,"    #declare lf_bound_y = lf_s_size*1.1/2\n");
  fprintf(File,"  #end\n");
  fprintf(File,"\n");
  fprintf(File,"  // ************* Arm pointing toward middle ************\n");
  fprintf(File,"  // *****************************************************\n");
  fprintf(File,"  #declare lf_new_disc_size = disc_size + .001 * lf_flares_drawn\n");
  fprintf(File,"\n");
  fprintf(File,"  #if (lf_pentagon=false)\n");
  fprintf(File,"  disc {\n");
  fprintf(File,"    <0,0,0>, z, lf_bound_y\n");
  fprintf(File,"  #else\n");
  fprintf(File,"  polygon {\n");
  fprintf(File,"    6,\n");
  fprintf(File,"    <0,-1>\n");
  fprintf(File,"    < cos(radians(18)),-sin(radians(18))>,\n");
  fprintf(File,"    < cos(radians(54)), sin(radians(54))>,\n");
  fprintf(File,"    <-cos(radians(54)), sin(radians(54))>,\n");
  fprintf(File,"    <-cos(radians(18)),-sin(radians(18))>,\n");
  fprintf(File,"    <0,-1>\n");
  fprintf(File,"    scale lf_s_size\n");
  fprintf(File,"  #end\n");
  fprintf(File,"    texture {\n");
  fprintf(File,"      pigment { lf_SpotPigment }\n");
  fprintf(File,"      finish { lf_Finish }\n");
  fprintf(File,"    }\n");
  fprintf(File,"    // *****************************************************************\n");
  fprintf(File,"    // ** calculate the apparant position of the flare spot\n");
  fprintf(File,"    // *****************************************************************\n");
  fprintf(File,"    #declare lf_2spot = lf_2light + (lf_newctr - lf_2light) * (spot_dist * pow(num_spots, spot_dist_pwr) + lf_s_dist)\n");
  fprintf(File,"\n");
  fprintf(File,"    scale lf_new_disc_size * flare_size\n");
  fprintf(File,"\n");
  fprintf(File,"    #if (spots_auto_rotate=true)\n");
  fprintf(File,"      rotate lf_rotate_ctr\n");
  fprintf(File,"    #else\n");
  fprintf(File,"      rotate lf_rotate_up\n");
  fprintf(File,"    #end\n");
  fprintf(File,"    rotate lf_rotate_x\n");
  fprintf(File,"    rotate lf_rotate_z\n");
  fprintf(File,"\n");
  fprintf(File,"    #declare lf_dist = 1/( vdot(lf_2spot,lf_2ctr)/(vlength(lf_2ctr)*vlength(lf_2spot)) )\n");
  fprintf(File,"    translate cam_loc + lf_new_disc_size * vnormalize(-lf_2spot)*lf_dist\n");
  fprintf(File,"    no_shadow hollow\n");
  fprintf(File,"  }\n");
  fprintf(File,"  #declare lf_flares_drawn = lf_flares_drawn + 1\n");
  fprintf(File,"\n");
  fprintf(File,"#if (num_spots <= opposite_spots) // !*!*!*!*!*!*!*!*!*!\n");
  fprintf(File,"  // *****************************************************************\n");
  fprintf(File,"  // ** randomly shift various attributes - again\n");
  fprintf(File,"  // *****************************************************************\n");
  fprintf(File,"  #declare lf_s_size  = spot_size + (rand(spot_seed) * 2 - 1) * spot_size_rand\n");
  fprintf(File,"  #declare lf_s_dist  = (rand(spot_seed) * 2 - 1) * spot_dist_rand\n");
  fprintf(File,"  #declare lf_s_color = spot_color + spot_color_rand * <(rand(spot_seed) * 2 - 1),(rand(spot_seed) * 2 - 1),(rand(spot_seed) * 2 - 1)>\n");
  fprintf(File,"  #declare lf_d_size  = dot_size + (rand(spot_seed) * 2 - 1) * dot_size_rand\n");
  fprintf(File,"  #declare lf_d_color = dot_color + dot_color_rand * <(rand(spot_seed) * 2 - 1),(rand(spot_seed) * 2 - 1),(rand(spot_seed) * 2 - 1)>\n");
  fprintf(File,"\n");
  fprintf(File,"  #declare lf_pentagon = false\n");
  fprintf(File,"\n");
  fprintf(File,"  #declare lf_is_dot = rand(spot_seed)\n");
  fprintf(File,"\n");
  fprintf(File,"  #switch (lf_is_dot)\n");
  fprintf(File,"  #range (0,percent_dots)\n");
  fprintf(File,"    #declare lf_SpotPigment = pigment {\n");
  fprintf(File,"      wood\n");
  fprintf(File,"      #declare tmp_tr = dot_tr + (1-dot_tr)*spot_fade_amount*(num_spots - skip_spots)\n");
  fprintf(File,"      color_map {\n");
  fprintf(File,"         [ 0.0                        color lf_d_color transmit tmp_tr         ]\n");
  fprintf(File,"         [ lf_d_size / 1.2            color lf_d_color transmit (1+tmp_tr)*.53 ]\n");
  fprintf(File,"         [ lf_d_size                  color lf_d_color transmit 1              ]\n");
  fprintf(File,"         [ 1 color rgbt <0,0,0,1> ]\n");
  fprintf(File,"      }\n");
  fprintf(File,"    }\n");
  fprintf(File,"    #declare lf_bound_y = lf_d_size/2\n");
  fprintf(File,"  #break\n");
  fprintf(File,"\n");
  fprintf(File,"  #range (percent_dots,percent_dots+percent_hex)\n");
  fprintf(File,"    #declare tmp_tr = spot_tr + (1-spot_tr)*spot_fade_amount*(num_spots - skip_spots)\n");
  fprintf(File,"    #declare lf_SpotPigment = pigment{hexagon lf_s_color transmit tmp_tr,rgbt<1,1,1,1>,rgbt<1,1,1,1> rotate 90*x scale .5*lf_s_size}\n");
  fprintf(File,"    #declare lf_bound_y = lf_s_size/2\n");
  fprintf(File,"  #break\n");
  fprintf(File,"\n");
  fprintf(File,"  #range (percent_dots+percent_hex,percent_dots+percent_hex+percent_pent)\n");
  fprintf(File,"    #declare lf_pentagon = true\n");
  fprintf(File,"    #declare tmp_tr = spot_tr + (1-spot_tr)*spot_fade_amount*(num_spots - skip_spots)\n");
  fprintf(File,"    #declare lf_SpotPigment = pigment{color lf_s_color transmit tmp_tr}\n");
  fprintf(File,"    #declare lf_bound_y = lf_s_size/2\n");
  fprintf(File,"  #break\n");
  fprintf(File,"\n");
  fprintf(File,"  #else\n");
  fprintf(File,"    #declare lf_SpotPigment = pigment {\n");
  fprintf(File,"      wood\n");
  fprintf(File,"      #declare tmp_tr = spot_tr + (1-spot_tr)*spot_fade_amount*(num_spots - skip_spots)\n");
  fprintf(File,"      color_map {\n");
  fprintf(File,"         [ 0.0                       color lf_s_color transmit 1              ]\n");
  fprintf(File,"         [ lf_s_size / 1.8           color lf_s_color transmit (1+tmp_tr)*.53 ]\n");
  fprintf(File,"         [ lf_s_size                 color lf_s_color transmit tmp_tr         ]\n");
  fprintf(File,"         [ lf_s_size +.1 * lf_s_size color lf_s_color transmit 1              ]\n");
  fprintf(File,"         [ 1 color rgbt <0,0,0,1> ]\n");
  fprintf(File,"      }\n");
  fprintf(File,"    }\n");
  fprintf(File,"    #declare lf_bound_y = lf_s_size*1.1/2\n");
  fprintf(File,"  #end\n");
  fprintf(File,"\n");
  fprintf(File,"  // ************* Arm pointing away *********************\n");
  fprintf(File,"  // *****************************************************\n");
  fprintf(File,"  #declare lf_new_disc_size = disc_size + .001 * lf_flares_drawn\n");
  fprintf(File,"\n");
  fprintf(File,"  #if (lf_pentagon=false)\n");
  fprintf(File,"  disc {\n");
  fprintf(File,"    <0,0,0>, z, lf_bound_y\n");
  fprintf(File,"  #else\n");
  fprintf(File,"  polygon {\n");
  fprintf(File,"    6,\n");
  fprintf(File,"    <0,-1>\n");
  fprintf(File,"    < cos(radians(18)),-sin(radians(18))>,\n");
  fprintf(File,"    < cos(radians(54)), sin(radians(54))>,\n");
  fprintf(File,"    <-cos(radians(54)), sin(radians(54))>,\n");
  fprintf(File,"    <-cos(radians(18)),-sin(radians(18))>,\n");
  fprintf(File,"    <0,-1>\n");
  fprintf(File,"    scale lf_s_size\n");
  fprintf(File,"  #end\n");
  fprintf(File,"    texture {\n");
  fprintf(File,"      pigment { lf_SpotPigment }\n");
  fprintf(File,"      finish { lf_Finish }\n");
  fprintf(File,"    }\n");
  fprintf(File,"    // *****************************************************************\n");
  fprintf(File,"    // ** calculate the apparant position of the flare spot\n");
  fprintf(File,"    // *****************************************************************\n");
  fprintf(File,"    #declare lf_2spot = lf_2light - (lf_newctr - lf_2light) * (spot_dist * pow(num_spots, spot_dist_pwr) + lf_s_dist)\n");
  fprintf(File,"\n");
  fprintf(File,"    scale lf_new_disc_size * flare_size\n");
  fprintf(File,"\n");
  fprintf(File,"    #if (spots_auto_rotate=true)\n");
  fprintf(File,"      rotate lf_rotate_ctr+180*z\n");
  fprintf(File,"    #else\n");
  fprintf(File,"      rotate lf_rotate_up\n");
  fprintf(File,"    #end\n");
  fprintf(File,"    rotate lf_rotate_x\n");
  fprintf(File,"    rotate lf_rotate_z\n");
  fprintf(File,"\n");
  fprintf(File,"    #declare lf_dist = 1/( vdot(lf_2spot,lf_2ctr)/(vlength(lf_2ctr)*vlength(lf_2spot)) )\n");
  fprintf(File,"    translate cam_loc + lf_new_disc_size * vnormalize(-lf_2spot)*lf_dist\n");
  fprintf(File,"    no_shadow hollow\n");
  fprintf(File,"  }\n");
  fprintf(File,"  #declare lf_flares_drawn = lf_flares_drawn + 1\n");
  fprintf(File,"\n");
  fprintf(File,"  #declare opposite_spots = opposite_spots - 1\n");
  fprintf(File,"#end\n");
  fprintf(File,"\n");
  fprintf(File,"  #declare num_spots = num_spots - 1\n");
  fprintf(File,"#end\n");
  fprintf(File,"\n");
  fprintf(File,"#ifdef (lf_50mm_spots)  #if (lf_50mm_spots = true)\n");
  fprintf(File,"  #declare lf_new_disc_size = disc_size + .001 * lf_flares_drawn\n");
  fprintf(File,"  disc {\n");
  fprintf(File,"    #declare lf_bound_y = ring_size*2.30/2\n");
  fprintf(File,"    <0,0,0>, z, lf_bound_y\n");
  fprintf(File,"    texture {\n");
  fprintf(File,"      // *****************************************************************\n");
  fprintf(File,"      // ***************** 50-300mm xtra large spot **********************\n");
  fprintf(File,"      // *****************************************************************\n");
  fprintf(File,"      pigment {\n");
  fprintf(File,"        wood\n");
  fprintf(File,"        color_map {\n");
  fprintf(File,"           [ 0.0              color transmit 1                ]\n");
  fprintf(File,"           [ ring_size*2      color <1,1,.7> transmit 1       ]\n");
  fprintf(File,"           [ ring_size*2.15   color <1,1,.7> transmit spot_tr ]\n");
  fprintf(File,"           [ ring_size*2.15   color <.8,.8,1> transmit spot_tr]\n");
  fprintf(File,"           [ ring_size*2.30   color <.8,.8,1> transmit 1      ]\n");
  fprintf(File,"           [ 1 color rgbt <0,0,0,1> ]\n");
  fprintf(File,"        }\n");
  fprintf(File,"      }\n");
  fprintf(File,"      finish { lf_Finish }\n");
  fprintf(File,"    }\n");
  fprintf(File,"    // *****************************************************************\n");
  fprintf(File,"    // ** calculate the apparant position of the flare spot\n");
  fprintf(File,"    // *****************************************************************\n");
  fprintf(File,"    #declare lf_2spot = lf_2light + (lf_newctr - lf_2light) * 2\n");
  fprintf(File,"\n");
  fprintf(File,"    scale lf_new_disc_size * flare_size\n");
  fprintf(File,"\n");
  fprintf(File,"    #if (flare_auto_rotate = false)\n");
  fprintf(File,"      rotate lf_rotate_up\n");
  fprintf(File,"    #else\n");
  fprintf(File,"      rotate lf_rotate_ctr\n");
  fprintf(File,"    #end\n");
  fprintf(File,"    rotate lf_rotate_x\n");
  fprintf(File,"    rotate lf_rotate_z\n");
  fprintf(File,"\n");
  fprintf(File,"    #declare lf_dist = 1/( vdot(lf_2spot,lf_2ctr)/(vlength(lf_2ctr)*vlength(lf_2spot)) )\n");
  fprintf(File,"    translate cam_loc + lf_new_disc_size * vnormalize(-lf_2spot)*lf_dist\n");
  fprintf(File,"    no_shadow hollow\n");
  fprintf(File,"  }\n");
  fprintf(File,"  #declare lf_flares_drawn = lf_flares_drawn + 1\n");
  fprintf(File,"#end #end\n");
  fprintf(File,"\n");
  fprintf(File,"#ifdef (lf_35mm_spots)  #if (lf_35mm_spots = true)\n");
  fprintf(File,"  #declare lf_new_disc_size = disc_size + .001 * lf_flares_drawn\n");
  fprintf(File,"  disc {\n");
  fprintf(File,"    #declare lf_bound_y = ring_size*2.15/2\n");
  fprintf(File,"    <0,0,0>, z, lf_bound_y\n");
  fprintf(File,"    texture {\n");
  fprintf(File,"      // *****************************************************************\n");
  fprintf(File,"      // ***************** 35mm xtra large spot **************************\n");
  fprintf(File,"      // *****************************************************************\n");
  fprintf(File,"      pigment {\n");
  fprintf(File,"        wood\n");
  fprintf(File,"        color_map {\n");
  fprintf(File,"           [ 0.0              color <.8,1,.8> transmit spot_tr*.95     ]\n");
  fprintf(File,"           [ ring_size/3      color <.8,1,.8> transmit spot_tr        ]\n");
  fprintf(File,"           [ ring_size*1.5    color <.8,1,.8> transmit (spot_tr+1)/2  ]\n");
  fprintf(File,"           [ ring_size*2      color <.8,1,.8> transmit spot_tr        ]\n");
  fprintf(File,"           [ ring_size*2.15   color <.8,1,.8> transmit 1              ]\n");
  fprintf(File,"           [ 1 color rgbt <0,0,0,1> ]\n");
  fprintf(File,"        }\n");
  fprintf(File,"      }\n");
  fprintf(File,"      finish { lf_Finish }\n");
  fprintf(File,"    }\n");
  fprintf(File,"    // *****************************************************************\n");
  fprintf(File,"    // ** calculate the apparant position of the flare spot\n");
  fprintf(File,"    // *****************************************************************\n");
  fprintf(File,"    #declare lf_2spot = lf_2light + (lf_newctr - lf_2light) * 2\n");
  fprintf(File,"\n");
  fprintf(File,"    scale lf_new_disc_size * flare_size\n");
  fprintf(File,"\n");
  fprintf(File,"    #if (flare_auto_rotate = false)\n");
  fprintf(File,"      rotate lf_rotate_up\n");
  fprintf(File,"    #else\n");
  fprintf(File,"      rotate lf_rotate_ctr\n");
  fprintf(File,"    #end\n");
  fprintf(File,"    rotate lf_rotate_x\n");
  fprintf(File,"    rotate lf_rotate_z\n");
  fprintf(File,"\n");
  fprintf(File,"    #declare lf_dist = 1/( vdot(lf_2spot,lf_2ctr)/(vlength(lf_2ctr)*vlength(lf_2spot)) )\n");
  fprintf(File,"    translate cam_loc + lf_new_disc_size * vnormalize(-lf_2spot)*lf_dist\n");
  fprintf(File,"    no_shadow hollow\n");
  fprintf(File,"  }\n");
  fprintf(File,"  #declare lf_flares_drawn = lf_flares_drawn + 1\n");
  fprintf(File,"#end #end\n");
  fprintf(File,"\n");
  fprintf(File,"#ifdef (lf_space_spots)  #if (lf_space_spots = true)\n");
  fprintf(File,"  #declare lf_new_disc_size = disc_size + .001 * lf_flares_drawn\n");
  fprintf(File,"  disc {\n");
  fprintf(File,"    #declare lf_bound_y = ring_size*2.30/2\n");
  fprintf(File,"    <0,0,0>, z, lf_bound_y\n");
  fprintf(File,"    texture {\n");
  fprintf(File,"      // *****************************************************************\n");
  fprintf(File,"      // ***************** anamorphic \"shadow\" 1    **********************\n");
  fprintf(File,"      // *****************************************************************\n");
  fprintf(File,"      pigment {\n");
  fprintf(File,"        wood\n");
  fprintf(File,"        color_map {\n");
  fprintf(File,"           [ 0.0              color transmit 1 ]\n");
  fprintf(File,"           [ ring_size        color ring_color transmit 1      ]\n");
  fprintf(File,"           [ ring_size*1.15   color ring_color transmit spot_tr*.98]\n");
  fprintf(File,"           [ ring_size*1.15   color ring_color transmit spot_tr*.98]\n");
  fprintf(File,"           [ ring_size*1.30   color ring_color transmit 1      ]\n");
  fprintf(File,"           [ 1 color rgbt <0,0,0,1> ]\n");
  fprintf(File,"        }\n");
  fprintf(File,"      }\n");
  fprintf(File,"      finish { lf_Finish }\n");
  fprintf(File,"    }\n");
  fprintf(File,"    // *****************************************************************\n");
  fprintf(File,"    // ** calculate the apparant position of the flare spot\n");
  fprintf(File,"    // *****************************************************************\n");
  fprintf(File,"    #declare lf_2spot = lf_2light + (lf_newctr - lf_2light) * 2\n");
  fprintf(File,"\n");
  fprintf(File,"    scale main_flare_scale * lf_new_disc_size * flare_size\n");
  fprintf(File,"\n");
  fprintf(File,"    #if (flare_auto_rotate = false)\n");
  fprintf(File,"      rotate lf_rotate_up\n");
  fprintf(File,"    #else\n");
  fprintf(File,"      rotate lf_rotate_ctr\n");
  fprintf(File,"    #end\n");
  fprintf(File,"    rotate lf_rotate_x\n");
  fprintf(File,"    rotate lf_rotate_z\n");
  fprintf(File,"\n");
  fprintf(File,"    #declare lf_dist = 1/( vdot(lf_2spot,lf_2ctr)/(vlength(lf_2ctr)*vlength(lf_2spot)) )\n");
  fprintf(File,"    translate cam_loc + lf_new_disc_size * vnormalize(-lf_2spot)*lf_dist\n");
  fprintf(File,"    no_shadow hollow\n");
  fprintf(File,"  }\n");
  fprintf(File,"  #declare lf_flares_drawn = lf_flares_drawn + 1\n");
  fprintf(File,"\n");
  fprintf(File,"  #declare lf_new_disc_size = disc_size + .001 * lf_flares_drawn\n");
  fprintf(File,"  disc {\n");
  fprintf(File,"    #declare lf_bound_y = ring_size*2.30/2\n");
  fprintf(File,"    <0,0,0>, z, lf_bound_y\n");
  fprintf(File,"    texture {\n");
  fprintf(File,"      // *****************************************************************\n");
  fprintf(File,"      // ***************** anamorphic \"shadow\" 2    **********************\n");
  fprintf(File,"      // *****************************************************************\n");
  fprintf(File,"      pigment {\n");
  fprintf(File,"        wood\n");
  fprintf(File,"        color_map {\n");
  fprintf(File,"           [ 0.0              color transmit 1 ]\n");
  fprintf(File,"           [ ring_size        color glow_color transmit 1      ]\n");
  fprintf(File,"           [ ring_size*1.15   color glow_color transmit spot_tr*.98]\n");
  fprintf(File,"           [ ring_size*1.15   color glow_color transmit spot_tr*.98]\n");
  fprintf(File,"           [ ring_size*1.30   color glow_color transmit 1      ]\n");
  fprintf(File,"           [ 1 color rgbt <0,0,0,1> ]\n");
  fprintf(File,"        }\n");
  fprintf(File,"      }\n");
  fprintf(File,"      finish { lf_Finish }\n");
  fprintf(File,"    }\n");
  fprintf(File,"    // *****************************************************************\n");
  fprintf(File,"    // ** calculate the apparant position of the flare spot\n");
  fprintf(File,"    // *****************************************************************\n");
  fprintf(File,"    #declare lf_2spot = lf_2light + (lf_newctr - lf_2light) * 2.02\n");
  fprintf(File,"\n");
  fprintf(File,"    scale main_flare_scale*.8 * lf_new_disc_size * flare_size\n");
  fprintf(File,"\n");
  fprintf(File,"    #if (flare_auto_rotate = false)\n");
  fprintf(File,"      rotate lf_rotate_up\n");
  fprintf(File,"    #else\n");
  fprintf(File,"      rotate lf_rotate_ctr\n");
  fprintf(File,"    #end\n");
  fprintf(File,"    rotate lf_rotate_x\n");
  fprintf(File,"    rotate lf_rotate_z\n");
  fprintf(File,"\n");
  fprintf(File,"    #declare lf_dist = 1/( vdot(lf_2spot,lf_2ctr)/(vlength(lf_2ctr)*vlength(lf_2spot)) )\n");
  fprintf(File,"    translate cam_loc + lf_new_disc_size * vnormalize(-lf_2spot)*lf_dist\n");
  fprintf(File,"    no_shadow hollow\n");
  fprintf(File,"  }\n");
  fprintf(File,"  #declare lf_flares_drawn = lf_flares_drawn + 1\n");
  fprintf(File,"\n");
  fprintf(File,"  #declare lf_new_disc_size = disc_size + .001 * lf_flares_drawn\n");
  fprintf(File,"  disc {\n");
  fprintf(File,"    <0,0,0>, z, .5\n");
  fprintf(File,"    texture {\n");
  fprintf(File,"      // *****************************************************************\n");
  fprintf(File,"      // ***************** anamorphic \"shadow\" 3    **********************\n");
  fprintf(File,"      // *****************************************************************\n");
  fprintf(File,"      pigment {\n");
  fprintf(File,"        wood\n");
  fprintf(File,"        color_map {\n");
  fprintf(File,"           [ 0.0           color streak_a_color transmit spot_tr*.9 ]\n");
  fprintf(File,"           [ 1.0  color streak_a_color transmit 1          ]\n");
  fprintf(File,"        }\n");
  fprintf(File,"      }\n");
  fprintf(File,"      finish { lf_Finish }\n");
  fprintf(File,"    }\n");
  fprintf(File,"    // *****************************************************************\n");
  fprintf(File,"    // ** calculate the apparant position of the flare spot\n");
  fprintf(File,"    // *****************************************************************\n");
  fprintf(File,"    #declare lf_2spot = lf_2light + (lf_newctr - lf_2light) * 1.8\n");
  fprintf(File,"\n");
  fprintf(File,"    scale streak_a_scale*<.2,1,1>* streak_a_size * lf_new_disc_size * flare_size\n");
  fprintf(File,"\n");
  fprintf(File,"    #if (streak_a_auto_rotate = false)\n");
  fprintf(File,"      rotate lf_rotate_up\n");
  fprintf(File,"    #else\n");
  fprintf(File,"      rotate lf_rotate_ctr\n");
  fprintf(File,"    #end\n");
  fprintf(File,"    rotate streak_a_rotate*z\n");
  fprintf(File,"    rotate lf_rotate_x\n");
  fprintf(File,"    rotate lf_rotate_z\n");
  fprintf(File,"\n");
  fprintf(File,"    #declare lf_dist = 1/( vdot(lf_2spot,lf_2ctr)/(vlength(lf_2ctr)*vlength(lf_2spot)) )\n");
  fprintf(File,"    translate cam_loc + lf_new_disc_size * vnormalize(-lf_2spot)*lf_dist\n");
  fprintf(File,"    no_shadow hollow\n");
  fprintf(File,"  }\n");
  fprintf(File,"#end #end\n");
  fprintf(File,"\n");
  fprintf(File,"#ifdef (lf_camcorder_spots)  #if (lf_camcorder_spots = true)\n");
  fprintf(File,"  #declare lf_new_disc_size = disc_size + .001 * lf_flares_drawn\n");
  fprintf(File,"  disc {\n");
  fprintf(File,"    #declare lf_bound_y = ring_size*1.15*1.5/2\n");
  fprintf(File,"    <0,0,0>, z, lf_bound_y\n");
  fprintf(File,"    texture {\n");
  fprintf(File,"      // *****************************************************************\n");
  fprintf(File,"      // ***************** camcorder xtra large spot *********************\n");
  fprintf(File,"      // *****************************************************************\n");
  fprintf(File,"      pigment {\n");
  fprintf(File,"        wood\n");
  fprintf(File,"        color_map {\n");
  fprintf(File,"           [ 0.0              color <.5,1,.9> transmit spot_tr]\n");
  fprintf(File,"           [ ring_size*0.90*1.5   color <.5,1,.9> transmit .95         ]\n");
  fprintf(File,"           [ ring_size*1.15*1.6   color <0,0,0> transmit 1          ]\n");
  fprintf(File,"           [ 1 color rgbt <0,0,0,1> ]\n");
  fprintf(File,"        }\n");
  fprintf(File,"      }\n");
  fprintf(File,"      finish { lf_Finish }\n");
  fprintf(File,"    }\n");
  fprintf(File,"    // *****************************************************************\n");
  fprintf(File,"    // ** calculate the apparant position of the flare spot\n");
  fprintf(File,"    // *****************************************************************\n");
  fprintf(File,"    #declare lf_2spot = lf_2light + (lf_newctr - lf_2light) * 2\n");
  fprintf(File,"\n");
  fprintf(File,"    scale lf_new_disc_size * flare_size\n");
  fprintf(File,"\n");
  fprintf(File,"    #if (flare_auto_rotate = false)\n");
  fprintf(File,"      rotate lf_rotate_up\n");
  fprintf(File,"    #else\n");
  fprintf(File,"      rotate lf_rotate_ctr\n");
  fprintf(File,"    #end\n");
  fprintf(File,"    rotate lf_rotate_x\n");
  fprintf(File,"    rotate lf_rotate_z\n");
  fprintf(File,"\n");
  fprintf(File,"    #declare lf_dist = 1/( vdot(lf_2spot,lf_2ctr)/(vlength(lf_2ctr)*vlength(lf_2spot)) )\n");
  fprintf(File,"    translate cam_loc + lf_new_disc_size * vnormalize(-lf_2spot)*lf_dist\n");
  fprintf(File,"    no_shadow hollow\n");
  fprintf(File,"  }\n");
  fprintf(File,"  #declare lf_flares_drawn = lf_flares_drawn + 1\n");
  fprintf(File,"\n");
  fprintf(File,"  #declare lf_new_disc_size = disc_size + .001 * lf_flares_drawn\n");
  fprintf(File,"  disc {\n");
  fprintf(File,"    #declare lf_bound_y = ring_size*0.9/2\n");
  fprintf(File,"    <0,0,0>, z, lf_bound_y\n");
  fprintf(File,"    texture {\n");
  fprintf(File,"      // *****************************************************************\n");
  fprintf(File,"      // ***************** camcorder xtra large spot *********************\n");
  fprintf(File,"      // *****************************************************************\n");
  fprintf(File,"      pigment {\n");
  fprintf(File,"        wood\n");
  fprintf(File,"        color_map {\n");
  fprintf(File,"           [ 0.0              color <1,.5,.5> transmit 1          ]\n");
  fprintf(File,"           [ ring_size*0.65   color <1,.5,.5> transmit .99        ]\n");
  fprintf(File,"           [ ring_size*0.85   color <1,.5,.5> transmit spot_tr]\n");
  fprintf(File,"           [ ring_size*0.90   color <1,.5,.5> transmit 1          ]\n");
  fprintf(File,"           [ 1 color rgbt <0,0,0,1> ]\n");
  fprintf(File,"        }\n");
  fprintf(File,"      }\n");
  fprintf(File,"      finish { lf_Finish }\n");
  fprintf(File,"    }\n");
  fprintf(File,"    // *****************************************************************\n");
  fprintf(File,"    // ** calculate the apparant position of the flare spot\n");
  fprintf(File,"    // *****************************************************************\n");
  fprintf(File,"    #declare lf_2spot = lf_2light + (lf_newctr - lf_2light) * 1.8\n");
  fprintf(File,"\n");
  fprintf(File,"    scale lf_new_disc_size * flare_size\n");
  fprintf(File,"\n");
  fprintf(File,"    #if (flare_auto_rotate = false)\n");
  fprintf(File,"      rotate lf_rotate_up\n");
  fprintf(File,"    #else\n");
  fprintf(File,"      rotate lf_rotate_ctr\n");
  fprintf(File,"    #end\n");
  fprintf(File,"    rotate lf_rotate_x\n");
  fprintf(File,"    rotate lf_rotate_z\n");
  fprintf(File,"\n");
  fprintf(File,"    #declare lf_dist = 1/( vdot(lf_2spot,lf_2ctr)/(vlength(lf_2ctr)*vlength(lf_2spot)) )\n");
  fprintf(File,"    translate cam_loc + lf_new_disc_size * vnormalize(-lf_2spot)*lf_dist\n");
  fprintf(File,"    no_shadow hollow\n");
  fprintf(File,"  }\n");
  fprintf(File,"  #declare lf_flares_drawn = lf_flares_drawn + 1\n");
  fprintf(File,"#end #end\n");
  fprintf(File,"#end  // if light was behind camera, lens flare was skipped.\n");
  fprintf(File,"\n");
  fprintf(File,"\n");
}
