.TH uglMesaGetDepthBuffer "3" "AOUT 2001" "WindML/Mesa" "WRS"

.SH NAME
uglMesaMoveGetDepthBuffer \- Return the depth buffer associated with an UGL/Mesa context

.SH SYNOPSIS
.B #include <GL/uglmesa.h>
.PP
.nf
.BI "GLboolean uglMesaGetDepthBuffer (GLint * " width ", GLint *" height ","
.BI "                                 GLint *" bytesPerValue ","
.BI "                                 void **" buffer );
.fi

.SH DESCRIPTION
The \fBuglMesaGetDepthBuffer\fR function returns the depth buffer associated with an UGL/Mesa context.

.SH INPUT VALUES
\fIwidth, height\fR - size of buffer in pixels
.PP
\fIbytesPerValue\fR - bytes per depth value (2 or 4)
.PP
\fIbuffer\fR - pointer to depth buffer values

.SH RETURN VALUES
GL_TRUE or GL_FALSE to indicate success or failure.

.SH COPYRIGHT
Copyright \(co 2001 Wind River Systems, Inc.
