.TH uglMesaGetCurrentContext "3" "AOUT 2001" "WindML/Mesa" "WRS"

.SH NAME
uglMesaGetCurrentContext \- Return the current UGL/Mesa context

.SH SYNOPSIS
.B #include <GL/uglmesa.h>
.PP
.BI "UGL_MESA_CONTEXT uglMesaGetCurrentContext (void);"

.SH DESCRIPTION
The \fBuglMesaGetCurrentContext\fR function returns the current
UGL/Mesa context.

.SH RETURN VALUES
a UGL/Mesa context, or NULL if error.

.SH SEE ALSO
.BR uglMesaMakeCurrentContext "(3)"

.SH COPYRIGHT
Copyright \(co 2001 Wind River Systems, Inc.
