name: 'Windows Build Compatibility Tests'

on:
  workflow_dispatch

jobs:
  build_windows:
    name: Visual Studio ${{ matrix.visual-studio }} ${{ matrix.configuration }} ${{ matrix.platform }} ${{ matrix.compatibility}}

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        visual-studio: [2015, 2017, 2019]
        variant: [64, sse2, 32]
        compatibility: ['', xp]
        exclude:
        - visual-studio: 2019
          compatibility: 'xp'
        include:
        # Set up various other options based on Visual Studio version to emulate
        - visual-studio: 2015
          os: windows-2016
          toolset: v140
          solution: vs2015
        - visual-studio: 2017
          os: windows-2016
          toolset: v141
          solution: vs2015
        - visual-studio: 2019
          os: windows-2019
          toolset: v142
          solution: vs2015
        # pick configuration / paltform combo
        - variant: 64
          configuration: Release
          platform: x64
        - variant: sse2
          configuration: Release-SSE2
          platform: Win32
        - variant: 32
          configuration: Release
          platform: Win32
        # Set up various other options based on compatibility requirements
        - compatibility: ''
          toolset-variant: ''
          msbuild-options: ''
        - compatibility: 'xp'
          toolset-variant: '_xp'
          msbuild-options: '/p:TargetUniversalCRTVersion=10.0.10586.0'

    steps:

    - name: 'Matrix Diagnostics'
      run: |
        echo "visual-studio:   '${{matrix.visual-studio}}'"
        echo "variant:         '${{matrix.variant}}'"
        echo "compatibility:   '${{matrix.compatibility}}'"
        echo "---"
        echo "os:              '${{matrix.os}}'"
        echo "solution:        '${{matrix.solution}}'"
        echo "configuration:   '${{matrix.configuration}}'"
        echo "platform:        '${{matrix.platform}}'"
        echo "toolset:         '${{matrix.toolset}}${{matrix.toolset-variant}}'"
        echo "msbuild-options: '${{matrix.msbuild-options}}'"

    - name: 'Check out Repository'
      uses: actions/checkout@v2

    - name: 'Add MSBuild to PATH'
      uses: microsoft/setup-msbuild@v1.0.2

    - name: 'Build'
      uses: POV-Ray/povray/.github/actions/windows_build@master
      with:
        pov-ray-build-id: ghvs${{matrix.visual-studio}}${{matrix.compatibility}}${{github.run_number}}
        solution: ${{matrix.solution}}
        configuration: ${{matrix.configuration}}
        platform: ${{matrix.platform}}
        toolset: ${{matrix.toolset}}${{matrix.toolset-variant}}
        msbuild-options: ${{matrix.msbuild-options}}
    - name: 'Sanity-Check Working Tree'
      uses: POV-Ray/povray/.github/actions/unix_check_repo@master
