name: 'Quick Tests'

on:
  workflow_dispatch:
  push:
    # For now, there's nothing in the following directories that we're actually checking.
    paths-ignore: [ 'distribution/**', 'doc/**', 'source-doc/**' ]
  pull_request:
    # For now, there's nothing in the following directories that we're actually checking.
    paths-ignore: [ 'distribution/**', 'doc/**', 'source-doc/**' ]

jobs:
  build_unix:
    name: 'Unix Build Test'
    runs-on: ubuntu-latest
    steps:

    - name: 'Check out Repository'
      uses: actions/checkout@v2

    - name: 'Install Prerequisites'
      uses: POV-Ray/povray/.github/actions/unix_getlibs@gh-actions-v1

    - name: 'Prebuild'
      uses: POV-Ray/povray/.github/actions/unix_prebuild@gh-actions-v1
    - name: 'Sanity-Check Working Tree'
      uses: POV-Ray/povray/.github/actions/git_check_repo@gh-actions-v1

    - name: 'Configure'
      uses: POV-Ray/povray/.github/actions/unix_configure@gh-actions-v1
    - name: 'Sanity-Check Working Tree'
      uses: POV-Ray/povray/.github/actions/git_check_repo@gh-actions-v1

    - name: 'Bundle Artifacts for Diagnostics'
      if: ${{ always() }}
      uses: POV-Ray/povray/.github/actions/git_bundle_ignored@gh-actions-v1
      with:
        name: artifact_diag_unix.tar.gz

    - name: 'Build'
      uses: POV-Ray/povray/.github/actions/unix_make@gh-actions-v1
    - name: 'Sanity-Check Working Tree'
      uses: POV-Ray/povray/.github/actions/git_check_repo@gh-actions-v1

    - name: 'Check Functionality'
      uses: POV-Ray/povray/.github/actions/unix_make@gh-actions-v1
      with:
        make-target: check
    - name: 'Sanity-Check Working Tree'
      uses: POV-Ray/povray/.github/actions/git_check_repo@gh-actions-v1

#    - name: 'Install'
#      uses: POV-Ray/povray/.github/actions/unix_make@gh-actions-v1
#      with:
#        make-target: install
#    - name: 'Sanity-Check Working Tree'
#      uses: POV-Ray/povray/.github/actions/git_check_repo@gh-actions-v1

    - name: 'Upload Artifacts for Diagnostics'
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: artifact_diag_unix
        path: artifact_diag_unix.tar.gz

    # TODO: Maybe do some basic installation checking.

  build_windows:
    name: 'Windows Build Test'
    runs-on: windows-latest
    steps:

    - name: 'Check out Repository'
      uses: actions/checkout@v2

    - name: 'Add MSBuild to PATH'
      uses: microsoft/setup-msbuild@v1.0.2

    - name: 'Build'
      uses: POV-Ray/povray/.github/actions/windows_build@gh-actions-v1
      with:
        pov-ray-build-id: gh${{github.run_number}}
        solution: vs2015
        configuration: Release
        platform: x64
        toolset: v142
        msbuild-options: ''
    - name: 'Sanity-Check Working Tree'
      uses: POV-Ray/povray/.github/actions/git_check_repo@gh-actions-v1
